driver:
  enabled: true
  version: "535.183.01"

toolkit:
  enabled: true

operator:
  defaultRuntime: containerd

devicePlugin:
  enabled: true

dcgmExporter:
  enabled: true
  repository: "nvcr.io/nvidia/k8s"
  image: "dcgm-exporter"
  version: "3.1.7-3.1.4-ubuntu20.04"
  
  # configure DCGM service
  service:
    enable: true
    port: 9400
    type: ClusterIP
    annotations: {}
    labels:
      app: nvidia-dcgm-exporter

gfd:
  enabled: true

migManager:
  enabled: false

nodeStatusExporter:
  enabled: true

validator:
  driver:
    enable: false
  toolkit:
    enable: false
  plugin:
    enable: false