apiVersion: v1
kind: Service
metadata:
  name: publicCloudLB-keepip-with-existing-ip
  labels:
    app: test-publicCloudLB
spec:
  loadBalancerIP: xx.xx.xx.xx # Public Floating IP you want to use. This annontation is deprecated since K8S 1.24 but still used
  ports:
  - name: client
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer
