- name: Wait for system to become reachable
  hosts: all
  gather_facts: no
  tasks:
  - name:
    ansible.builtin.wait_for_connection:
- name: Install K3S dependancies
  hosts: all
  become: yes
  tasks:
  - name: Installing dependancies
    ansible.builtin.apt:
      pkg:
      - curl
  - name: Install K3S
    ansible.builtin.get_url:
      url: https://get.k3s.io
      dest: /home/ubuntu/installK3s.sh
      mode: '0755'
  - name: Run installK3s.sh
    command: /home/ubuntu/installK3s.sh
  - replace:
      path: /etc/rancher/k3s/k3s.yaml
      regexp: '127.0.0.1'
      replace: '{{ ansible_ens3.ipv4.address }}'
  - name: Storing in a path relative to the playbook
    ansible.builtin.fetch:
      src: /etc/rancher/k3s/k3s.yaml
      dest: config-{{ ansible_hostname }}
      flat: yes

