module "s3_user" {
  source = "./modules/s3_user"
}

module "kubeflow" {
  source = "./modules/kubeflow"
  ovh_s3_access_key                    = module.s3_user.access_key_id
  ovh_s3_secret_key                    = module.s3_user.secret_access_key
  ovh_dns_domain                       = var.ovh_dns_domain
  ovh_api_dns_application_key          = var.ovh_api_dns_application_key
  ovh_api_dns_consumer_key             = var.ovh_api_dns_consumer_key
  ovh_api_dns_application_secret       = var.ovh_api_dns_application_secret
  ovh_os_region_name                   = var.ovh_os_region_name
  ovh_os_private_network_vlan_id       = var.ovh_os_private_network_vlan_id
  ovh_gateway_size                     = var.ovh_gateway_size
  ovh_kube_cluster_name                = var.ovh_kube_cluster_name
  ovh_kube_version                     = var.ovh_kube_version
  kubeflow_control_plane_flavor        = var.kubeflow_control_plane_flavor
  kubeflow_control_plane_autoscale     = var.kubeflow_control_plane_autoscale
  kubeflow_control_plane_desired_nodes = var.kubeflow_control_plane_desired_nodes
  kubeflow_control_plane_max_nodes     = var.kubeflow_control_plane_max_nodes
  kubeflow_control_plane_min_nodes     = var.kubeflow_control_plane_min_nodes
  kubeflow_cpu_worker_flavor           = var.kubeflow_cpu_worker_flavor
  kubeflow_cpu_worker_autoscale        = var.kubeflow_cpu_worker_autoscale
  kubeflow_cpu_worker_desired_nodes    = var.kubeflow_cpu_worker_desired_nodes
  kubeflow_cpu_worker_max_nodes        = var.kubeflow_cpu_worker_max_nodes
  kubeflow_cpu_worker_min_nodes        = var.kubeflow_cpu_worker_min_nodes
  kubeflow_gpu_worker_flavor           = var.kubeflow_gpu_worker_flavor
  kubeflow_gpu_worker_autoscale        = var.kubeflow_gpu_worker_autoscale
  kubeflow_gpu_worker_max_nodes        = var.kubeflow_gpu_worker_max_nodes
  kubeflow_gpu_worker_min_nodes        = var.kubeflow_gpu_worker_min_nodes
  letsencrypt_issuer                   = var.letsencrypt_issuer
  ovh_mysql_name                       = var.ovh_mysql_name
  ovh_mysql_version                    = var.ovh_mysql_version
  ovh_mysql_region                     = var.ovh_mysql_region
  ovh_s3_bucket_name                   = var.ovh_s3_bucket_name
  ovh_s3_region_name                   = var.ovh_s3_region_name
  kubeflow_default_user_name           = var.kubeflow_default_user_name
  kubeflow_default_user_password_hash  = var.kubeflow_default_user_password_hash
}