apiVersion: v1
kind: Service
metadata:
  name: publicCloudLB-small-to-upgrade
  labels:
    app: test-publicCloudLB
spec:
  ports:
    - name: client
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer
