prometheus:
  enabled: true
  prometheusSpec:
    retention: 7d
    scrapeInterval: 30s
    evaluationInterval: 30s
    
    serviceMonitorNamespaceSelector: {}
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorNamespaceSelector: {}
    podMonitorSelectorNilUsesHelmValues: false
    
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 2Gi
    
    storageSpec: {}

grafana:
  enabled: true
  adminPassword: "Admin123!vLLM"    # replace by your own password
  
  sidecar:
    datasources:
      enabled: false
  
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-kube-prometheus-prometheus.monitoring:9090
        access: proxy
        isDefault: true
        editable: true
        jsonData:
          timeInterval: 30s
  
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  
  persistence:
    enabled: false
  
  initChownData:
    enabled: false
  
  testFramework:
    enabled: false
  
  securityContext:
    runAsNonRoot: false
    runAsUser: 472
    fsGroup: 472

alertmanager:
  enabled: false

nodeExporter:
  enabled: true

kubeStateMetrics:
  enabled: true

prometheusOperator:
  enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

defaultRules:
  create: false