// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package ovh

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/ovh/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type CloudProjectNetworkPrivate struct {
	pulumi.CustomResourceState

	Name              pulumi.StringOutput                                   `pulumi:"name"`
	Regions           pulumi.StringArrayOutput                              `pulumi:"regions"`
	RegionsAttributes CloudProjectNetworkPrivateRegionsAttributeArrayOutput `pulumi:"regionsAttributes"`
	// Deprecated: Deprecated
	RegionsStatuses CloudProjectNetworkPrivateRegionsStatusArrayOutput `pulumi:"regionsStatuses"`
	// Service name of the resource representing the id of the cloud project.
	ServiceName pulumi.StringPtrOutput  `pulumi:"serviceName"`
	Status      pulumi.StringOutput     `pulumi:"status"`
	Type        pulumi.StringOutput     `pulumi:"type"`
	VlanId      pulumi.Float64PtrOutput `pulumi:"vlanId"`
}

// NewCloudProjectNetworkPrivate registers a new resource with the given unique name, arguments, and options.
func NewCloudProjectNetworkPrivate(ctx *pulumi.Context,
	name string, args *CloudProjectNetworkPrivateArgs, opts ...pulumi.ResourceOption) (*CloudProjectNetworkPrivate, error) {
	if args == nil {
		args = &CloudProjectNetworkPrivateArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource CloudProjectNetworkPrivate
	err = ctx.RegisterPackageResource("ovh:index/cloudProjectNetworkPrivate:CloudProjectNetworkPrivate", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetCloudProjectNetworkPrivate gets an existing CloudProjectNetworkPrivate resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetCloudProjectNetworkPrivate(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *CloudProjectNetworkPrivateState, opts ...pulumi.ResourceOption) (*CloudProjectNetworkPrivate, error) {
	var resource CloudProjectNetworkPrivate
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("ovh:index/cloudProjectNetworkPrivate:CloudProjectNetworkPrivate", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering CloudProjectNetworkPrivate resources.
type cloudProjectNetworkPrivateState struct {
	Name              *string                                      `pulumi:"name"`
	Regions           []string                                     `pulumi:"regions"`
	RegionsAttributes []CloudProjectNetworkPrivateRegionsAttribute `pulumi:"regionsAttributes"`
	// Deprecated: Deprecated
	RegionsStatuses []CloudProjectNetworkPrivateRegionsStatus `pulumi:"regionsStatuses"`
	// Service name of the resource representing the id of the cloud project.
	ServiceName *string  `pulumi:"serviceName"`
	Status      *string  `pulumi:"status"`
	Type        *string  `pulumi:"type"`
	VlanId      *float64 `pulumi:"vlanId"`
}

type CloudProjectNetworkPrivateState struct {
	Name              pulumi.StringPtrInput
	Regions           pulumi.StringArrayInput
	RegionsAttributes CloudProjectNetworkPrivateRegionsAttributeArrayInput
	// Deprecated: Deprecated
	RegionsStatuses CloudProjectNetworkPrivateRegionsStatusArrayInput
	// Service name of the resource representing the id of the cloud project.
	ServiceName pulumi.StringPtrInput
	Status      pulumi.StringPtrInput
	Type        pulumi.StringPtrInput
	VlanId      pulumi.Float64PtrInput
}

func (CloudProjectNetworkPrivateState) ElementType() reflect.Type {
	return reflect.TypeOf((*cloudProjectNetworkPrivateState)(nil)).Elem()
}

type cloudProjectNetworkPrivateArgs struct {
	Name    *string  `pulumi:"name"`
	Regions []string `pulumi:"regions"`
	// Service name of the resource representing the id of the cloud project.
	ServiceName *string  `pulumi:"serviceName"`
	VlanId      *float64 `pulumi:"vlanId"`
}

// The set of arguments for constructing a CloudProjectNetworkPrivate resource.
type CloudProjectNetworkPrivateArgs struct {
	Name    pulumi.StringPtrInput
	Regions pulumi.StringArrayInput
	// Service name of the resource representing the id of the cloud project.
	ServiceName pulumi.StringPtrInput
	VlanId      pulumi.Float64PtrInput
}

func (CloudProjectNetworkPrivateArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*cloudProjectNetworkPrivateArgs)(nil)).Elem()
}

type CloudProjectNetworkPrivateInput interface {
	pulumi.Input

	ToCloudProjectNetworkPrivateOutput() CloudProjectNetworkPrivateOutput
	ToCloudProjectNetworkPrivateOutputWithContext(ctx context.Context) CloudProjectNetworkPrivateOutput
}

func (*CloudProjectNetworkPrivate) ElementType() reflect.Type {
	return reflect.TypeOf((**CloudProjectNetworkPrivate)(nil)).Elem()
}

func (i *CloudProjectNetworkPrivate) ToCloudProjectNetworkPrivateOutput() CloudProjectNetworkPrivateOutput {
	return i.ToCloudProjectNetworkPrivateOutputWithContext(context.Background())
}

func (i *CloudProjectNetworkPrivate) ToCloudProjectNetworkPrivateOutputWithContext(ctx context.Context) CloudProjectNetworkPrivateOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CloudProjectNetworkPrivateOutput)
}

type CloudProjectNetworkPrivateOutput struct{ *pulumi.OutputState }

func (CloudProjectNetworkPrivateOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**CloudProjectNetworkPrivate)(nil)).Elem()
}

func (o CloudProjectNetworkPrivateOutput) ToCloudProjectNetworkPrivateOutput() CloudProjectNetworkPrivateOutput {
	return o
}

func (o CloudProjectNetworkPrivateOutput) ToCloudProjectNetworkPrivateOutputWithContext(ctx context.Context) CloudProjectNetworkPrivateOutput {
	return o
}

func (o CloudProjectNetworkPrivateOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *CloudProjectNetworkPrivate) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func (o CloudProjectNetworkPrivateOutput) Regions() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *CloudProjectNetworkPrivate) pulumi.StringArrayOutput { return v.Regions }).(pulumi.StringArrayOutput)
}

func (o CloudProjectNetworkPrivateOutput) RegionsAttributes() CloudProjectNetworkPrivateRegionsAttributeArrayOutput {
	return o.ApplyT(func(v *CloudProjectNetworkPrivate) CloudProjectNetworkPrivateRegionsAttributeArrayOutput {
		return v.RegionsAttributes
	}).(CloudProjectNetworkPrivateRegionsAttributeArrayOutput)
}

// Deprecated: Deprecated
func (o CloudProjectNetworkPrivateOutput) RegionsStatuses() CloudProjectNetworkPrivateRegionsStatusArrayOutput {
	return o.ApplyT(func(v *CloudProjectNetworkPrivate) CloudProjectNetworkPrivateRegionsStatusArrayOutput {
		return v.RegionsStatuses
	}).(CloudProjectNetworkPrivateRegionsStatusArrayOutput)
}

// Service name of the resource representing the id of the cloud project.
func (o CloudProjectNetworkPrivateOutput) ServiceName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *CloudProjectNetworkPrivate) pulumi.StringPtrOutput { return v.ServiceName }).(pulumi.StringPtrOutput)
}

func (o CloudProjectNetworkPrivateOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v *CloudProjectNetworkPrivate) pulumi.StringOutput { return v.Status }).(pulumi.StringOutput)
}

func (o CloudProjectNetworkPrivateOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v *CloudProjectNetworkPrivate) pulumi.StringOutput { return v.Type }).(pulumi.StringOutput)
}

func (o CloudProjectNetworkPrivateOutput) VlanId() pulumi.Float64PtrOutput {
	return o.ApplyT(func(v *CloudProjectNetworkPrivate) pulumi.Float64PtrOutput { return v.VlanId }).(pulumi.Float64PtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*CloudProjectNetworkPrivateInput)(nil)).Elem(), &CloudProjectNetworkPrivate{})
	pulumi.RegisterOutputType(CloudProjectNetworkPrivateOutput{})
}
