// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package ovh

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/ovh/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type DbaasLogsCluster struct {
	pulumi.CustomResourceState

	// Allowed networks for ARCHIVE flow type
	ArchiveAllowedNetworks pulumi.StringArrayOutput `pulumi:"archiveAllowedNetworks"`
	ClusterId              pulumi.StringPtrOutput   `pulumi:"clusterId"`
	// Cluster type
	ClusterType pulumi.StringOutput `pulumi:"clusterType"`
	// PEM for dedicated inputs
	DedicatedInputPem pulumi.StringOutput `pulumi:"dedicatedInputPem"`
	// Allowed networks for DIRECT_INPUT flow type
	DirectInputAllowedNetworks pulumi.StringArrayOutput `pulumi:"directInputAllowedNetworks"`
	// PEM for direct inputs
	DirectInputPem pulumi.StringOutput `pulumi:"directInputPem"`
	// hostname
	Hostname pulumi.StringOutput `pulumi:"hostname"`
	// Initial allowed networks for ARCHIVE flow type
	InitialArchiveAllowedNetworks pulumi.StringArrayOutput `pulumi:"initialArchiveAllowedNetworks"`
	// Initial allowed networks for DIRECT_INPUT flow type
	InitialDirectInputAllowedNetworks pulumi.StringArrayOutput `pulumi:"initialDirectInputAllowedNetworks"`
	// Initial allowed networks for QUERY flow type
	InitialQueryAllowedNetworks pulumi.StringArrayOutput `pulumi:"initialQueryAllowedNetworks"`
	// All content generated by given service will be placed on this cluster
	IsDefault pulumi.BoolOutput `pulumi:"isDefault"`
	// Allow given service to perform advanced operations on cluster
	IsUnlocked pulumi.BoolOutput `pulumi:"isUnlocked"`
	// Allowed networks for QUERY flow type
	QueryAllowedNetworks pulumi.StringArrayOutput `pulumi:"queryAllowedNetworks"`
	// Data center localization
	Region      pulumi.StringOutput `pulumi:"region"`
	ServiceName pulumi.StringOutput `pulumi:"serviceName"`
}

// NewDbaasLogsCluster registers a new resource with the given unique name, arguments, and options.
func NewDbaasLogsCluster(ctx *pulumi.Context,
	name string, args *DbaasLogsClusterArgs, opts ...pulumi.ResourceOption) (*DbaasLogsCluster, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ServiceName == nil {
		return nil, errors.New("invalid value for required argument 'ServiceName'")
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"dedicatedInputPem",
		"directInputPem",
		"initialArchiveAllowedNetworks",
		"initialDirectInputAllowedNetworks",
		"initialQueryAllowedNetworks",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource DbaasLogsCluster
	err = ctx.RegisterPackageResource("ovh:index/dbaasLogsCluster:DbaasLogsCluster", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetDbaasLogsCluster gets an existing DbaasLogsCluster resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetDbaasLogsCluster(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *DbaasLogsClusterState, opts ...pulumi.ResourceOption) (*DbaasLogsCluster, error) {
	var resource DbaasLogsCluster
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("ovh:index/dbaasLogsCluster:DbaasLogsCluster", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering DbaasLogsCluster resources.
type dbaasLogsClusterState struct {
	// Allowed networks for ARCHIVE flow type
	ArchiveAllowedNetworks []string `pulumi:"archiveAllowedNetworks"`
	ClusterId              *string  `pulumi:"clusterId"`
	// Cluster type
	ClusterType *string `pulumi:"clusterType"`
	// PEM for dedicated inputs
	DedicatedInputPem *string `pulumi:"dedicatedInputPem"`
	// Allowed networks for DIRECT_INPUT flow type
	DirectInputAllowedNetworks []string `pulumi:"directInputAllowedNetworks"`
	// PEM for direct inputs
	DirectInputPem *string `pulumi:"directInputPem"`
	// hostname
	Hostname *string `pulumi:"hostname"`
	// Initial allowed networks for ARCHIVE flow type
	InitialArchiveAllowedNetworks []string `pulumi:"initialArchiveAllowedNetworks"`
	// Initial allowed networks for DIRECT_INPUT flow type
	InitialDirectInputAllowedNetworks []string `pulumi:"initialDirectInputAllowedNetworks"`
	// Initial allowed networks for QUERY flow type
	InitialQueryAllowedNetworks []string `pulumi:"initialQueryAllowedNetworks"`
	// All content generated by given service will be placed on this cluster
	IsDefault *bool `pulumi:"isDefault"`
	// Allow given service to perform advanced operations on cluster
	IsUnlocked *bool `pulumi:"isUnlocked"`
	// Allowed networks for QUERY flow type
	QueryAllowedNetworks []string `pulumi:"queryAllowedNetworks"`
	// Data center localization
	Region      *string `pulumi:"region"`
	ServiceName *string `pulumi:"serviceName"`
}

type DbaasLogsClusterState struct {
	// Allowed networks for ARCHIVE flow type
	ArchiveAllowedNetworks pulumi.StringArrayInput
	ClusterId              pulumi.StringPtrInput
	// Cluster type
	ClusterType pulumi.StringPtrInput
	// PEM for dedicated inputs
	DedicatedInputPem pulumi.StringPtrInput
	// Allowed networks for DIRECT_INPUT flow type
	DirectInputAllowedNetworks pulumi.StringArrayInput
	// PEM for direct inputs
	DirectInputPem pulumi.StringPtrInput
	// hostname
	Hostname pulumi.StringPtrInput
	// Initial allowed networks for ARCHIVE flow type
	InitialArchiveAllowedNetworks pulumi.StringArrayInput
	// Initial allowed networks for DIRECT_INPUT flow type
	InitialDirectInputAllowedNetworks pulumi.StringArrayInput
	// Initial allowed networks for QUERY flow type
	InitialQueryAllowedNetworks pulumi.StringArrayInput
	// All content generated by given service will be placed on this cluster
	IsDefault pulumi.BoolPtrInput
	// Allow given service to perform advanced operations on cluster
	IsUnlocked pulumi.BoolPtrInput
	// Allowed networks for QUERY flow type
	QueryAllowedNetworks pulumi.StringArrayInput
	// Data center localization
	Region      pulumi.StringPtrInput
	ServiceName pulumi.StringPtrInput
}

func (DbaasLogsClusterState) ElementType() reflect.Type {
	return reflect.TypeOf((*dbaasLogsClusterState)(nil)).Elem()
}

type dbaasLogsClusterArgs struct {
	// Allowed networks for ARCHIVE flow type
	ArchiveAllowedNetworks []string `pulumi:"archiveAllowedNetworks"`
	ClusterId              *string  `pulumi:"clusterId"`
	// Allowed networks for DIRECT_INPUT flow type
	DirectInputAllowedNetworks []string `pulumi:"directInputAllowedNetworks"`
	// Allowed networks for QUERY flow type
	QueryAllowedNetworks []string `pulumi:"queryAllowedNetworks"`
	ServiceName          string   `pulumi:"serviceName"`
}

// The set of arguments for constructing a DbaasLogsCluster resource.
type DbaasLogsClusterArgs struct {
	// Allowed networks for ARCHIVE flow type
	ArchiveAllowedNetworks pulumi.StringArrayInput
	ClusterId              pulumi.StringPtrInput
	// Allowed networks for DIRECT_INPUT flow type
	DirectInputAllowedNetworks pulumi.StringArrayInput
	// Allowed networks for QUERY flow type
	QueryAllowedNetworks pulumi.StringArrayInput
	ServiceName          pulumi.StringInput
}

func (DbaasLogsClusterArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*dbaasLogsClusterArgs)(nil)).Elem()
}

type DbaasLogsClusterInput interface {
	pulumi.Input

	ToDbaasLogsClusterOutput() DbaasLogsClusterOutput
	ToDbaasLogsClusterOutputWithContext(ctx context.Context) DbaasLogsClusterOutput
}

func (*DbaasLogsCluster) ElementType() reflect.Type {
	return reflect.TypeOf((**DbaasLogsCluster)(nil)).Elem()
}

func (i *DbaasLogsCluster) ToDbaasLogsClusterOutput() DbaasLogsClusterOutput {
	return i.ToDbaasLogsClusterOutputWithContext(context.Background())
}

func (i *DbaasLogsCluster) ToDbaasLogsClusterOutputWithContext(ctx context.Context) DbaasLogsClusterOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DbaasLogsClusterOutput)
}

type DbaasLogsClusterOutput struct{ *pulumi.OutputState }

func (DbaasLogsClusterOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**DbaasLogsCluster)(nil)).Elem()
}

func (o DbaasLogsClusterOutput) ToDbaasLogsClusterOutput() DbaasLogsClusterOutput {
	return o
}

func (o DbaasLogsClusterOutput) ToDbaasLogsClusterOutputWithContext(ctx context.Context) DbaasLogsClusterOutput {
	return o
}

// Allowed networks for ARCHIVE flow type
func (o DbaasLogsClusterOutput) ArchiveAllowedNetworks() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *DbaasLogsCluster) pulumi.StringArrayOutput { return v.ArchiveAllowedNetworks }).(pulumi.StringArrayOutput)
}

func (o DbaasLogsClusterOutput) ClusterId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DbaasLogsCluster) pulumi.StringPtrOutput { return v.ClusterId }).(pulumi.StringPtrOutput)
}

// Cluster type
func (o DbaasLogsClusterOutput) ClusterType() pulumi.StringOutput {
	return o.ApplyT(func(v *DbaasLogsCluster) pulumi.StringOutput { return v.ClusterType }).(pulumi.StringOutput)
}

// PEM for dedicated inputs
func (o DbaasLogsClusterOutput) DedicatedInputPem() pulumi.StringOutput {
	return o.ApplyT(func(v *DbaasLogsCluster) pulumi.StringOutput { return v.DedicatedInputPem }).(pulumi.StringOutput)
}

// Allowed networks for DIRECT_INPUT flow type
func (o DbaasLogsClusterOutput) DirectInputAllowedNetworks() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *DbaasLogsCluster) pulumi.StringArrayOutput { return v.DirectInputAllowedNetworks }).(pulumi.StringArrayOutput)
}

// PEM for direct inputs
func (o DbaasLogsClusterOutput) DirectInputPem() pulumi.StringOutput {
	return o.ApplyT(func(v *DbaasLogsCluster) pulumi.StringOutput { return v.DirectInputPem }).(pulumi.StringOutput)
}

// hostname
func (o DbaasLogsClusterOutput) Hostname() pulumi.StringOutput {
	return o.ApplyT(func(v *DbaasLogsCluster) pulumi.StringOutput { return v.Hostname }).(pulumi.StringOutput)
}

// Initial allowed networks for ARCHIVE flow type
func (o DbaasLogsClusterOutput) InitialArchiveAllowedNetworks() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *DbaasLogsCluster) pulumi.StringArrayOutput { return v.InitialArchiveAllowedNetworks }).(pulumi.StringArrayOutput)
}

// Initial allowed networks for DIRECT_INPUT flow type
func (o DbaasLogsClusterOutput) InitialDirectInputAllowedNetworks() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *DbaasLogsCluster) pulumi.StringArrayOutput { return v.InitialDirectInputAllowedNetworks }).(pulumi.StringArrayOutput)
}

// Initial allowed networks for QUERY flow type
func (o DbaasLogsClusterOutput) InitialQueryAllowedNetworks() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *DbaasLogsCluster) pulumi.StringArrayOutput { return v.InitialQueryAllowedNetworks }).(pulumi.StringArrayOutput)
}

// All content generated by given service will be placed on this cluster
func (o DbaasLogsClusterOutput) IsDefault() pulumi.BoolOutput {
	return o.ApplyT(func(v *DbaasLogsCluster) pulumi.BoolOutput { return v.IsDefault }).(pulumi.BoolOutput)
}

// Allow given service to perform advanced operations on cluster
func (o DbaasLogsClusterOutput) IsUnlocked() pulumi.BoolOutput {
	return o.ApplyT(func(v *DbaasLogsCluster) pulumi.BoolOutput { return v.IsUnlocked }).(pulumi.BoolOutput)
}

// Allowed networks for QUERY flow type
func (o DbaasLogsClusterOutput) QueryAllowedNetworks() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *DbaasLogsCluster) pulumi.StringArrayOutput { return v.QueryAllowedNetworks }).(pulumi.StringArrayOutput)
}

// Data center localization
func (o DbaasLogsClusterOutput) Region() pulumi.StringOutput {
	return o.ApplyT(func(v *DbaasLogsCluster) pulumi.StringOutput { return v.Region }).(pulumi.StringOutput)
}

func (o DbaasLogsClusterOutput) ServiceName() pulumi.StringOutput {
	return o.ApplyT(func(v *DbaasLogsCluster) pulumi.StringOutput { return v.ServiceName }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*DbaasLogsClusterInput)(nil)).Elem(), &DbaasLogsCluster{})
	pulumi.RegisterOutputType(DbaasLogsClusterOutput{})
}
