// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package ovh

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/ovh/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupCloudProjectContainerregistryOidc(ctx *pulumi.Context, args *LookupCloudProjectContainerregistryOidcArgs, opts ...pulumi.InvokeOption) (*LookupCloudProjectContainerregistryOidcResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv LookupCloudProjectContainerregistryOidcResult
	err = ctx.InvokePackage("ovh:index/getCloudProjectContainerregistryOidc:getCloudProjectContainerregistryOidc", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getCloudProjectContainerregistryOidc.
type LookupCloudProjectContainerregistryOidcArgs struct {
	Id              *string `pulumi:"id"`
	OidcAdminGroup  *string `pulumi:"oidcAdminGroup"`
	OidcAutoOnboard *bool   `pulumi:"oidcAutoOnboard"`
	OidcClientId    *string `pulumi:"oidcClientId"`
	OidcEndpoint    *string `pulumi:"oidcEndpoint"`
	OidcGroupsClaim *string `pulumi:"oidcGroupsClaim"`
	OidcName        *string `pulumi:"oidcName"`
	OidcScope       *string `pulumi:"oidcScope"`
	OidcUserClaim   *string `pulumi:"oidcUserClaim"`
	OidcVerifyCert  *bool   `pulumi:"oidcVerifyCert"`
	RegistryId      string  `pulumi:"registryId"`
	ServiceName     *string `pulumi:"serviceName"`
}

// A collection of values returned by getCloudProjectContainerregistryOidc.
type LookupCloudProjectContainerregistryOidcResult struct {
	Id              string  `pulumi:"id"`
	OidcAdminGroup  *string `pulumi:"oidcAdminGroup"`
	OidcAutoOnboard *bool   `pulumi:"oidcAutoOnboard"`
	OidcClientId    *string `pulumi:"oidcClientId"`
	OidcEndpoint    *string `pulumi:"oidcEndpoint"`
	OidcGroupsClaim *string `pulumi:"oidcGroupsClaim"`
	OidcName        *string `pulumi:"oidcName"`
	OidcScope       *string `pulumi:"oidcScope"`
	OidcUserClaim   *string `pulumi:"oidcUserClaim"`
	OidcVerifyCert  *bool   `pulumi:"oidcVerifyCert"`
	RegistryId      string  `pulumi:"registryId"`
	ServiceName     *string `pulumi:"serviceName"`
}

func LookupCloudProjectContainerregistryOidcOutput(ctx *pulumi.Context, args LookupCloudProjectContainerregistryOidcOutputArgs, opts ...pulumi.InvokeOption) LookupCloudProjectContainerregistryOidcResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupCloudProjectContainerregistryOidcResult, error) {
			args := v.(LookupCloudProjectContainerregistryOidcArgs)
			r, err := LookupCloudProjectContainerregistryOidc(ctx, &args, opts...)
			var s LookupCloudProjectContainerregistryOidcResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupCloudProjectContainerregistryOidcResultOutput)
}

// A collection of arguments for invoking getCloudProjectContainerregistryOidc.
type LookupCloudProjectContainerregistryOidcOutputArgs struct {
	Id              pulumi.StringPtrInput `pulumi:"id"`
	OidcAdminGroup  pulumi.StringPtrInput `pulumi:"oidcAdminGroup"`
	OidcAutoOnboard pulumi.BoolPtrInput   `pulumi:"oidcAutoOnboard"`
	OidcClientId    pulumi.StringPtrInput `pulumi:"oidcClientId"`
	OidcEndpoint    pulumi.StringPtrInput `pulumi:"oidcEndpoint"`
	OidcGroupsClaim pulumi.StringPtrInput `pulumi:"oidcGroupsClaim"`
	OidcName        pulumi.StringPtrInput `pulumi:"oidcName"`
	OidcScope       pulumi.StringPtrInput `pulumi:"oidcScope"`
	OidcUserClaim   pulumi.StringPtrInput `pulumi:"oidcUserClaim"`
	OidcVerifyCert  pulumi.BoolPtrInput   `pulumi:"oidcVerifyCert"`
	RegistryId      pulumi.StringInput    `pulumi:"registryId"`
	ServiceName     pulumi.StringPtrInput `pulumi:"serviceName"`
}

func (LookupCloudProjectContainerregistryOidcOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupCloudProjectContainerregistryOidcArgs)(nil)).Elem()
}

// A collection of values returned by getCloudProjectContainerregistryOidc.
type LookupCloudProjectContainerregistryOidcResultOutput struct{ *pulumi.OutputState }

func (LookupCloudProjectContainerregistryOidcResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupCloudProjectContainerregistryOidcResult)(nil)).Elem()
}

func (o LookupCloudProjectContainerregistryOidcResultOutput) ToLookupCloudProjectContainerregistryOidcResultOutput() LookupCloudProjectContainerregistryOidcResultOutput {
	return o
}

func (o LookupCloudProjectContainerregistryOidcResultOutput) ToLookupCloudProjectContainerregistryOidcResultOutputWithContext(ctx context.Context) LookupCloudProjectContainerregistryOidcResultOutput {
	return o
}

func (o LookupCloudProjectContainerregistryOidcResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCloudProjectContainerregistryOidcResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupCloudProjectContainerregistryOidcResultOutput) OidcAdminGroup() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupCloudProjectContainerregistryOidcResult) *string { return v.OidcAdminGroup }).(pulumi.StringPtrOutput)
}

func (o LookupCloudProjectContainerregistryOidcResultOutput) OidcAutoOnboard() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v LookupCloudProjectContainerregistryOidcResult) *bool { return v.OidcAutoOnboard }).(pulumi.BoolPtrOutput)
}

func (o LookupCloudProjectContainerregistryOidcResultOutput) OidcClientId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupCloudProjectContainerregistryOidcResult) *string { return v.OidcClientId }).(pulumi.StringPtrOutput)
}

func (o LookupCloudProjectContainerregistryOidcResultOutput) OidcEndpoint() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupCloudProjectContainerregistryOidcResult) *string { return v.OidcEndpoint }).(pulumi.StringPtrOutput)
}

func (o LookupCloudProjectContainerregistryOidcResultOutput) OidcGroupsClaim() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupCloudProjectContainerregistryOidcResult) *string { return v.OidcGroupsClaim }).(pulumi.StringPtrOutput)
}

func (o LookupCloudProjectContainerregistryOidcResultOutput) OidcName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupCloudProjectContainerregistryOidcResult) *string { return v.OidcName }).(pulumi.StringPtrOutput)
}

func (o LookupCloudProjectContainerregistryOidcResultOutput) OidcScope() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupCloudProjectContainerregistryOidcResult) *string { return v.OidcScope }).(pulumi.StringPtrOutput)
}

func (o LookupCloudProjectContainerregistryOidcResultOutput) OidcUserClaim() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupCloudProjectContainerregistryOidcResult) *string { return v.OidcUserClaim }).(pulumi.StringPtrOutput)
}

func (o LookupCloudProjectContainerregistryOidcResultOutput) OidcVerifyCert() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v LookupCloudProjectContainerregistryOidcResult) *bool { return v.OidcVerifyCert }).(pulumi.BoolPtrOutput)
}

func (o LookupCloudProjectContainerregistryOidcResultOutput) RegistryId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCloudProjectContainerregistryOidcResult) string { return v.RegistryId }).(pulumi.StringOutput)
}

func (o LookupCloudProjectContainerregistryOidcResultOutput) ServiceName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupCloudProjectContainerregistryOidcResult) *string { return v.ServiceName }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupCloudProjectContainerregistryOidcResultOutput{})
}
