// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package ovh

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/ovh/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetCloudProjectKubeNodes(ctx *pulumi.Context, args *GetCloudProjectKubeNodesArgs, opts ...pulumi.InvokeOption) (*GetCloudProjectKubeNodesResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv GetCloudProjectKubeNodesResult
	err = ctx.InvokePackage("ovh:index/getCloudProjectKubeNodes:getCloudProjectKubeNodes", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getCloudProjectKubeNodes.
type GetCloudProjectKubeNodesArgs struct {
	Id          *string `pulumi:"id"`
	KubeId      string  `pulumi:"kubeId"`
	ServiceName *string `pulumi:"serviceName"`
}

// A collection of values returned by getCloudProjectKubeNodes.
type GetCloudProjectKubeNodesResult struct {
	Id          string                         `pulumi:"id"`
	KubeId      string                         `pulumi:"kubeId"`
	Nodes       []GetCloudProjectKubeNodesNode `pulumi:"nodes"`
	ServiceName *string                        `pulumi:"serviceName"`
}

func GetCloudProjectKubeNodesOutput(ctx *pulumi.Context, args GetCloudProjectKubeNodesOutputArgs, opts ...pulumi.InvokeOption) GetCloudProjectKubeNodesResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetCloudProjectKubeNodesResult, error) {
			args := v.(GetCloudProjectKubeNodesArgs)
			r, err := GetCloudProjectKubeNodes(ctx, &args, opts...)
			var s GetCloudProjectKubeNodesResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetCloudProjectKubeNodesResultOutput)
}

// A collection of arguments for invoking getCloudProjectKubeNodes.
type GetCloudProjectKubeNodesOutputArgs struct {
	Id          pulumi.StringPtrInput `pulumi:"id"`
	KubeId      pulumi.StringInput    `pulumi:"kubeId"`
	ServiceName pulumi.StringPtrInput `pulumi:"serviceName"`
}

func (GetCloudProjectKubeNodesOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetCloudProjectKubeNodesArgs)(nil)).Elem()
}

// A collection of values returned by getCloudProjectKubeNodes.
type GetCloudProjectKubeNodesResultOutput struct{ *pulumi.OutputState }

func (GetCloudProjectKubeNodesResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetCloudProjectKubeNodesResult)(nil)).Elem()
}

func (o GetCloudProjectKubeNodesResultOutput) ToGetCloudProjectKubeNodesResultOutput() GetCloudProjectKubeNodesResultOutput {
	return o
}

func (o GetCloudProjectKubeNodesResultOutput) ToGetCloudProjectKubeNodesResultOutputWithContext(ctx context.Context) GetCloudProjectKubeNodesResultOutput {
	return o
}

func (o GetCloudProjectKubeNodesResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetCloudProjectKubeNodesResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetCloudProjectKubeNodesResultOutput) KubeId() pulumi.StringOutput {
	return o.ApplyT(func(v GetCloudProjectKubeNodesResult) string { return v.KubeId }).(pulumi.StringOutput)
}

func (o GetCloudProjectKubeNodesResultOutput) Nodes() GetCloudProjectKubeNodesNodeArrayOutput {
	return o.ApplyT(func(v GetCloudProjectKubeNodesResult) []GetCloudProjectKubeNodesNode { return v.Nodes }).(GetCloudProjectKubeNodesNodeArrayOutput)
}

func (o GetCloudProjectKubeNodesResultOutput) ServiceName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetCloudProjectKubeNodesResult) *string { return v.ServiceName }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(GetCloudProjectKubeNodesResultOutput{})
}
