// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package ovh

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/ovh/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetCloudProjectDatabaseKafkaSchemaregistryacls(ctx *pulumi.Context, args *GetCloudProjectDatabaseKafkaSchemaregistryaclsArgs, opts ...pulumi.InvokeOption) (*GetCloudProjectDatabaseKafkaSchemaregistryaclsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv GetCloudProjectDatabaseKafkaSchemaregistryaclsResult
	err = ctx.InvokePackage("ovh:index/getCloudProjectDatabaseKafkaSchemaregistryacls:getCloudProjectDatabaseKafkaSchemaregistryacls", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getCloudProjectDatabaseKafkaSchemaregistryacls.
type GetCloudProjectDatabaseKafkaSchemaregistryaclsArgs struct {
	ClusterId   string  `pulumi:"clusterId"`
	Id          *string `pulumi:"id"`
	ServiceName *string `pulumi:"serviceName"`
}

// A collection of values returned by getCloudProjectDatabaseKafkaSchemaregistryacls.
type GetCloudProjectDatabaseKafkaSchemaregistryaclsResult struct {
	AclIds      []string `pulumi:"aclIds"`
	ClusterId   string   `pulumi:"clusterId"`
	Id          string   `pulumi:"id"`
	ServiceName *string  `pulumi:"serviceName"`
}

func GetCloudProjectDatabaseKafkaSchemaregistryaclsOutput(ctx *pulumi.Context, args GetCloudProjectDatabaseKafkaSchemaregistryaclsOutputArgs, opts ...pulumi.InvokeOption) GetCloudProjectDatabaseKafkaSchemaregistryaclsResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetCloudProjectDatabaseKafkaSchemaregistryaclsResult, error) {
			args := v.(GetCloudProjectDatabaseKafkaSchemaregistryaclsArgs)
			r, err := GetCloudProjectDatabaseKafkaSchemaregistryacls(ctx, &args, opts...)
			var s GetCloudProjectDatabaseKafkaSchemaregistryaclsResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetCloudProjectDatabaseKafkaSchemaregistryaclsResultOutput)
}

// A collection of arguments for invoking getCloudProjectDatabaseKafkaSchemaregistryacls.
type GetCloudProjectDatabaseKafkaSchemaregistryaclsOutputArgs struct {
	ClusterId   pulumi.StringInput    `pulumi:"clusterId"`
	Id          pulumi.StringPtrInput `pulumi:"id"`
	ServiceName pulumi.StringPtrInput `pulumi:"serviceName"`
}

func (GetCloudProjectDatabaseKafkaSchemaregistryaclsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetCloudProjectDatabaseKafkaSchemaregistryaclsArgs)(nil)).Elem()
}

// A collection of values returned by getCloudProjectDatabaseKafkaSchemaregistryacls.
type GetCloudProjectDatabaseKafkaSchemaregistryaclsResultOutput struct{ *pulumi.OutputState }

func (GetCloudProjectDatabaseKafkaSchemaregistryaclsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetCloudProjectDatabaseKafkaSchemaregistryaclsResult)(nil)).Elem()
}

func (o GetCloudProjectDatabaseKafkaSchemaregistryaclsResultOutput) ToGetCloudProjectDatabaseKafkaSchemaregistryaclsResultOutput() GetCloudProjectDatabaseKafkaSchemaregistryaclsResultOutput {
	return o
}

func (o GetCloudProjectDatabaseKafkaSchemaregistryaclsResultOutput) ToGetCloudProjectDatabaseKafkaSchemaregistryaclsResultOutputWithContext(ctx context.Context) GetCloudProjectDatabaseKafkaSchemaregistryaclsResultOutput {
	return o
}

func (o GetCloudProjectDatabaseKafkaSchemaregistryaclsResultOutput) AclIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetCloudProjectDatabaseKafkaSchemaregistryaclsResult) []string { return v.AclIds }).(pulumi.StringArrayOutput)
}

func (o GetCloudProjectDatabaseKafkaSchemaregistryaclsResultOutput) ClusterId() pulumi.StringOutput {
	return o.ApplyT(func(v GetCloudProjectDatabaseKafkaSchemaregistryaclsResult) string { return v.ClusterId }).(pulumi.StringOutput)
}

func (o GetCloudProjectDatabaseKafkaSchemaregistryaclsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetCloudProjectDatabaseKafkaSchemaregistryaclsResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetCloudProjectDatabaseKafkaSchemaregistryaclsResultOutput) ServiceName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetCloudProjectDatabaseKafkaSchemaregistryaclsResult) *string { return v.ServiceName }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(GetCloudProjectDatabaseKafkaSchemaregistryaclsResultOutput{})
}
