// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package ovh

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/ovh/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetCloudProjectDatabaseIpRestrictions(ctx *pulumi.Context, args *GetCloudProjectDatabaseIpRestrictionsArgs, opts ...pulumi.InvokeOption) (*GetCloudProjectDatabaseIpRestrictionsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv GetCloudProjectDatabaseIpRestrictionsResult
	err = ctx.InvokePackage("ovh:index/getCloudProjectDatabaseIpRestrictions:getCloudProjectDatabaseIpRestrictions", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getCloudProjectDatabaseIpRestrictions.
type GetCloudProjectDatabaseIpRestrictionsArgs struct {
	ClusterId   string  `pulumi:"clusterId"`
	Engine      string  `pulumi:"engine"`
	ServiceName *string `pulumi:"serviceName"`
}

// A collection of values returned by getCloudProjectDatabaseIpRestrictions.
type GetCloudProjectDatabaseIpRestrictionsResult struct {
	ClusterId string `pulumi:"clusterId"`
	Engine    string `pulumi:"engine"`
	// The provider-assigned unique ID for this managed resource.
	Id          string   `pulumi:"id"`
	Ips         []string `pulumi:"ips"`
	ServiceName *string  `pulumi:"serviceName"`
}

func GetCloudProjectDatabaseIpRestrictionsOutput(ctx *pulumi.Context, args GetCloudProjectDatabaseIpRestrictionsOutputArgs, opts ...pulumi.InvokeOption) GetCloudProjectDatabaseIpRestrictionsResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetCloudProjectDatabaseIpRestrictionsResult, error) {
			args := v.(GetCloudProjectDatabaseIpRestrictionsArgs)
			r, err := GetCloudProjectDatabaseIpRestrictions(ctx, &args, opts...)
			var s GetCloudProjectDatabaseIpRestrictionsResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetCloudProjectDatabaseIpRestrictionsResultOutput)
}

// A collection of arguments for invoking getCloudProjectDatabaseIpRestrictions.
type GetCloudProjectDatabaseIpRestrictionsOutputArgs struct {
	ClusterId   pulumi.StringInput    `pulumi:"clusterId"`
	Engine      pulumi.StringInput    `pulumi:"engine"`
	ServiceName pulumi.StringPtrInput `pulumi:"serviceName"`
}

func (GetCloudProjectDatabaseIpRestrictionsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetCloudProjectDatabaseIpRestrictionsArgs)(nil)).Elem()
}

// A collection of values returned by getCloudProjectDatabaseIpRestrictions.
type GetCloudProjectDatabaseIpRestrictionsResultOutput struct{ *pulumi.OutputState }

func (GetCloudProjectDatabaseIpRestrictionsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetCloudProjectDatabaseIpRestrictionsResult)(nil)).Elem()
}

func (o GetCloudProjectDatabaseIpRestrictionsResultOutput) ToGetCloudProjectDatabaseIpRestrictionsResultOutput() GetCloudProjectDatabaseIpRestrictionsResultOutput {
	return o
}

func (o GetCloudProjectDatabaseIpRestrictionsResultOutput) ToGetCloudProjectDatabaseIpRestrictionsResultOutputWithContext(ctx context.Context) GetCloudProjectDatabaseIpRestrictionsResultOutput {
	return o
}

func (o GetCloudProjectDatabaseIpRestrictionsResultOutput) ClusterId() pulumi.StringOutput {
	return o.ApplyT(func(v GetCloudProjectDatabaseIpRestrictionsResult) string { return v.ClusterId }).(pulumi.StringOutput)
}

func (o GetCloudProjectDatabaseIpRestrictionsResultOutput) Engine() pulumi.StringOutput {
	return o.ApplyT(func(v GetCloudProjectDatabaseIpRestrictionsResult) string { return v.Engine }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetCloudProjectDatabaseIpRestrictionsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetCloudProjectDatabaseIpRestrictionsResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetCloudProjectDatabaseIpRestrictionsResultOutput) Ips() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetCloudProjectDatabaseIpRestrictionsResult) []string { return v.Ips }).(pulumi.StringArrayOutput)
}

func (o GetCloudProjectDatabaseIpRestrictionsResultOutput) ServiceName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetCloudProjectDatabaseIpRestrictionsResult) *string { return v.ServiceName }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(GetCloudProjectDatabaseIpRestrictionsResultOutput{})
}
