// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package ovh

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/ovh/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupCloudProjectUserS3Credential(ctx *pulumi.Context, args *LookupCloudProjectUserS3CredentialArgs, opts ...pulumi.InvokeOption) (*LookupCloudProjectUserS3CredentialResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv LookupCloudProjectUserS3CredentialResult
	err = ctx.InvokePackage("ovh:index/getCloudProjectUserS3Credential:getCloudProjectUserS3Credential", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getCloudProjectUserS3Credential.
type LookupCloudProjectUserS3CredentialArgs struct {
	AccessKeyId string  `pulumi:"accessKeyId"`
	Id          *string `pulumi:"id"`
	ServiceName *string `pulumi:"serviceName"`
	UserId      string  `pulumi:"userId"`
}

// A collection of values returned by getCloudProjectUserS3Credential.
type LookupCloudProjectUserS3CredentialResult struct {
	AccessKeyId     string  `pulumi:"accessKeyId"`
	Id              string  `pulumi:"id"`
	SecretAccessKey string  `pulumi:"secretAccessKey"`
	ServiceName     *string `pulumi:"serviceName"`
	UserId          string  `pulumi:"userId"`
}

func LookupCloudProjectUserS3CredentialOutput(ctx *pulumi.Context, args LookupCloudProjectUserS3CredentialOutputArgs, opts ...pulumi.InvokeOption) LookupCloudProjectUserS3CredentialResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupCloudProjectUserS3CredentialResult, error) {
			args := v.(LookupCloudProjectUserS3CredentialArgs)
			r, err := LookupCloudProjectUserS3Credential(ctx, &args, opts...)
			var s LookupCloudProjectUserS3CredentialResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupCloudProjectUserS3CredentialResultOutput)
}

// A collection of arguments for invoking getCloudProjectUserS3Credential.
type LookupCloudProjectUserS3CredentialOutputArgs struct {
	AccessKeyId pulumi.StringInput    `pulumi:"accessKeyId"`
	Id          pulumi.StringPtrInput `pulumi:"id"`
	ServiceName pulumi.StringPtrInput `pulumi:"serviceName"`
	UserId      pulumi.StringInput    `pulumi:"userId"`
}

func (LookupCloudProjectUserS3CredentialOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupCloudProjectUserS3CredentialArgs)(nil)).Elem()
}

// A collection of values returned by getCloudProjectUserS3Credential.
type LookupCloudProjectUserS3CredentialResultOutput struct{ *pulumi.OutputState }

func (LookupCloudProjectUserS3CredentialResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupCloudProjectUserS3CredentialResult)(nil)).Elem()
}

func (o LookupCloudProjectUserS3CredentialResultOutput) ToLookupCloudProjectUserS3CredentialResultOutput() LookupCloudProjectUserS3CredentialResultOutput {
	return o
}

func (o LookupCloudProjectUserS3CredentialResultOutput) ToLookupCloudProjectUserS3CredentialResultOutputWithContext(ctx context.Context) LookupCloudProjectUserS3CredentialResultOutput {
	return o
}

func (o LookupCloudProjectUserS3CredentialResultOutput) AccessKeyId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCloudProjectUserS3CredentialResult) string { return v.AccessKeyId }).(pulumi.StringOutput)
}

func (o LookupCloudProjectUserS3CredentialResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCloudProjectUserS3CredentialResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupCloudProjectUserS3CredentialResultOutput) SecretAccessKey() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCloudProjectUserS3CredentialResult) string { return v.SecretAccessKey }).(pulumi.StringOutput)
}

func (o LookupCloudProjectUserS3CredentialResultOutput) ServiceName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupCloudProjectUserS3CredentialResult) *string { return v.ServiceName }).(pulumi.StringPtrOutput)
}

func (o LookupCloudProjectUserS3CredentialResultOutput) UserId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCloudProjectUserS3CredentialResult) string { return v.UserId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupCloudProjectUserS3CredentialResultOutput{})
}
