// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package ovh

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/ovh/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupCloudProjectKubeIprestrictions(ctx *pulumi.Context, args *LookupCloudProjectKubeIprestrictionsArgs, opts ...pulumi.InvokeOption) (*LookupCloudProjectKubeIprestrictionsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv LookupCloudProjectKubeIprestrictionsResult
	err = ctx.InvokePackage("ovh:index/getCloudProjectKubeIprestrictions:getCloudProjectKubeIprestrictions", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getCloudProjectKubeIprestrictions.
type LookupCloudProjectKubeIprestrictionsArgs struct {
	Id          *string `pulumi:"id"`
	KubeId      string  `pulumi:"kubeId"`
	ServiceName *string `pulumi:"serviceName"`
}

// A collection of values returned by getCloudProjectKubeIprestrictions.
type LookupCloudProjectKubeIprestrictionsResult struct {
	Id          string   `pulumi:"id"`
	Ips         []string `pulumi:"ips"`
	KubeId      string   `pulumi:"kubeId"`
	ServiceName *string  `pulumi:"serviceName"`
}

func LookupCloudProjectKubeIprestrictionsOutput(ctx *pulumi.Context, args LookupCloudProjectKubeIprestrictionsOutputArgs, opts ...pulumi.InvokeOption) LookupCloudProjectKubeIprestrictionsResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupCloudProjectKubeIprestrictionsResult, error) {
			args := v.(LookupCloudProjectKubeIprestrictionsArgs)
			r, err := LookupCloudProjectKubeIprestrictions(ctx, &args, opts...)
			var s LookupCloudProjectKubeIprestrictionsResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupCloudProjectKubeIprestrictionsResultOutput)
}

// A collection of arguments for invoking getCloudProjectKubeIprestrictions.
type LookupCloudProjectKubeIprestrictionsOutputArgs struct {
	Id          pulumi.StringPtrInput `pulumi:"id"`
	KubeId      pulumi.StringInput    `pulumi:"kubeId"`
	ServiceName pulumi.StringPtrInput `pulumi:"serviceName"`
}

func (LookupCloudProjectKubeIprestrictionsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupCloudProjectKubeIprestrictionsArgs)(nil)).Elem()
}

// A collection of values returned by getCloudProjectKubeIprestrictions.
type LookupCloudProjectKubeIprestrictionsResultOutput struct{ *pulumi.OutputState }

func (LookupCloudProjectKubeIprestrictionsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupCloudProjectKubeIprestrictionsResult)(nil)).Elem()
}

func (o LookupCloudProjectKubeIprestrictionsResultOutput) ToLookupCloudProjectKubeIprestrictionsResultOutput() LookupCloudProjectKubeIprestrictionsResultOutput {
	return o
}

func (o LookupCloudProjectKubeIprestrictionsResultOutput) ToLookupCloudProjectKubeIprestrictionsResultOutputWithContext(ctx context.Context) LookupCloudProjectKubeIprestrictionsResultOutput {
	return o
}

func (o LookupCloudProjectKubeIprestrictionsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCloudProjectKubeIprestrictionsResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupCloudProjectKubeIprestrictionsResultOutput) Ips() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupCloudProjectKubeIprestrictionsResult) []string { return v.Ips }).(pulumi.StringArrayOutput)
}

func (o LookupCloudProjectKubeIprestrictionsResultOutput) KubeId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCloudProjectKubeIprestrictionsResult) string { return v.KubeId }).(pulumi.StringOutput)
}

func (o LookupCloudProjectKubeIprestrictionsResultOutput) ServiceName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupCloudProjectKubeIprestrictionsResult) *string { return v.ServiceName }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupCloudProjectKubeIprestrictionsResultOutput{})
}
