// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package ovh

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/ovh/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetCloudProjectDatabaseLogSubscriptions(ctx *pulumi.Context, args *GetCloudProjectDatabaseLogSubscriptionsArgs, opts ...pulumi.InvokeOption) (*GetCloudProjectDatabaseLogSubscriptionsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv GetCloudProjectDatabaseLogSubscriptionsResult
	err = ctx.InvokePackage("ovh:index/getCloudProjectDatabaseLogSubscriptions:getCloudProjectDatabaseLogSubscriptions", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getCloudProjectDatabaseLogSubscriptions.
type GetCloudProjectDatabaseLogSubscriptionsArgs struct {
	ClusterId   string  `pulumi:"clusterId"`
	Engine      string  `pulumi:"engine"`
	Id          *string `pulumi:"id"`
	ServiceName *string `pulumi:"serviceName"`
}

// A collection of values returned by getCloudProjectDatabaseLogSubscriptions.
type GetCloudProjectDatabaseLogSubscriptionsResult struct {
	ClusterId       string   `pulumi:"clusterId"`
	Engine          string   `pulumi:"engine"`
	Id              string   `pulumi:"id"`
	ServiceName     *string  `pulumi:"serviceName"`
	SubscriptionIds []string `pulumi:"subscriptionIds"`
}

func GetCloudProjectDatabaseLogSubscriptionsOutput(ctx *pulumi.Context, args GetCloudProjectDatabaseLogSubscriptionsOutputArgs, opts ...pulumi.InvokeOption) GetCloudProjectDatabaseLogSubscriptionsResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetCloudProjectDatabaseLogSubscriptionsResult, error) {
			args := v.(GetCloudProjectDatabaseLogSubscriptionsArgs)
			r, err := GetCloudProjectDatabaseLogSubscriptions(ctx, &args, opts...)
			var s GetCloudProjectDatabaseLogSubscriptionsResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetCloudProjectDatabaseLogSubscriptionsResultOutput)
}

// A collection of arguments for invoking getCloudProjectDatabaseLogSubscriptions.
type GetCloudProjectDatabaseLogSubscriptionsOutputArgs struct {
	ClusterId   pulumi.StringInput    `pulumi:"clusterId"`
	Engine      pulumi.StringInput    `pulumi:"engine"`
	Id          pulumi.StringPtrInput `pulumi:"id"`
	ServiceName pulumi.StringPtrInput `pulumi:"serviceName"`
}

func (GetCloudProjectDatabaseLogSubscriptionsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetCloudProjectDatabaseLogSubscriptionsArgs)(nil)).Elem()
}

// A collection of values returned by getCloudProjectDatabaseLogSubscriptions.
type GetCloudProjectDatabaseLogSubscriptionsResultOutput struct{ *pulumi.OutputState }

func (GetCloudProjectDatabaseLogSubscriptionsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetCloudProjectDatabaseLogSubscriptionsResult)(nil)).Elem()
}

func (o GetCloudProjectDatabaseLogSubscriptionsResultOutput) ToGetCloudProjectDatabaseLogSubscriptionsResultOutput() GetCloudProjectDatabaseLogSubscriptionsResultOutput {
	return o
}

func (o GetCloudProjectDatabaseLogSubscriptionsResultOutput) ToGetCloudProjectDatabaseLogSubscriptionsResultOutputWithContext(ctx context.Context) GetCloudProjectDatabaseLogSubscriptionsResultOutput {
	return o
}

func (o GetCloudProjectDatabaseLogSubscriptionsResultOutput) ClusterId() pulumi.StringOutput {
	return o.ApplyT(func(v GetCloudProjectDatabaseLogSubscriptionsResult) string { return v.ClusterId }).(pulumi.StringOutput)
}

func (o GetCloudProjectDatabaseLogSubscriptionsResultOutput) Engine() pulumi.StringOutput {
	return o.ApplyT(func(v GetCloudProjectDatabaseLogSubscriptionsResult) string { return v.Engine }).(pulumi.StringOutput)
}

func (o GetCloudProjectDatabaseLogSubscriptionsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetCloudProjectDatabaseLogSubscriptionsResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetCloudProjectDatabaseLogSubscriptionsResultOutput) ServiceName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetCloudProjectDatabaseLogSubscriptionsResult) *string { return v.ServiceName }).(pulumi.StringPtrOutput)
}

func (o GetCloudProjectDatabaseLogSubscriptionsResultOutput) SubscriptionIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetCloudProjectDatabaseLogSubscriptionsResult) []string { return v.SubscriptionIds }).(pulumi.StringArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetCloudProjectDatabaseLogSubscriptionsResultOutput{})
}
