// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package ovh

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/ovh/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupCloudProjectDatabaseOpensearchPattern(ctx *pulumi.Context, args *LookupCloudProjectDatabaseOpensearchPatternArgs, opts ...pulumi.InvokeOption) (*LookupCloudProjectDatabaseOpensearchPatternResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv LookupCloudProjectDatabaseOpensearchPatternResult
	err = ctx.InvokePackage("ovh:index/getCloudProjectDatabaseOpensearchPattern:getCloudProjectDatabaseOpensearchPattern", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getCloudProjectDatabaseOpensearchPattern.
type LookupCloudProjectDatabaseOpensearchPatternArgs struct {
	ClusterId   string  `pulumi:"clusterId"`
	Id          string  `pulumi:"id"`
	ServiceName *string `pulumi:"serviceName"`
}

// A collection of values returned by getCloudProjectDatabaseOpensearchPattern.
type LookupCloudProjectDatabaseOpensearchPatternResult struct {
	ClusterId     string  `pulumi:"clusterId"`
	Id            string  `pulumi:"id"`
	MaxIndexCount float64 `pulumi:"maxIndexCount"`
	Pattern       string  `pulumi:"pattern"`
	ServiceName   *string `pulumi:"serviceName"`
}

func LookupCloudProjectDatabaseOpensearchPatternOutput(ctx *pulumi.Context, args LookupCloudProjectDatabaseOpensearchPatternOutputArgs, opts ...pulumi.InvokeOption) LookupCloudProjectDatabaseOpensearchPatternResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupCloudProjectDatabaseOpensearchPatternResult, error) {
			args := v.(LookupCloudProjectDatabaseOpensearchPatternArgs)
			r, err := LookupCloudProjectDatabaseOpensearchPattern(ctx, &args, opts...)
			var s LookupCloudProjectDatabaseOpensearchPatternResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupCloudProjectDatabaseOpensearchPatternResultOutput)
}

// A collection of arguments for invoking getCloudProjectDatabaseOpensearchPattern.
type LookupCloudProjectDatabaseOpensearchPatternOutputArgs struct {
	ClusterId   pulumi.StringInput    `pulumi:"clusterId"`
	Id          pulumi.StringInput    `pulumi:"id"`
	ServiceName pulumi.StringPtrInput `pulumi:"serviceName"`
}

func (LookupCloudProjectDatabaseOpensearchPatternOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupCloudProjectDatabaseOpensearchPatternArgs)(nil)).Elem()
}

// A collection of values returned by getCloudProjectDatabaseOpensearchPattern.
type LookupCloudProjectDatabaseOpensearchPatternResultOutput struct{ *pulumi.OutputState }

func (LookupCloudProjectDatabaseOpensearchPatternResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupCloudProjectDatabaseOpensearchPatternResult)(nil)).Elem()
}

func (o LookupCloudProjectDatabaseOpensearchPatternResultOutput) ToLookupCloudProjectDatabaseOpensearchPatternResultOutput() LookupCloudProjectDatabaseOpensearchPatternResultOutput {
	return o
}

func (o LookupCloudProjectDatabaseOpensearchPatternResultOutput) ToLookupCloudProjectDatabaseOpensearchPatternResultOutputWithContext(ctx context.Context) LookupCloudProjectDatabaseOpensearchPatternResultOutput {
	return o
}

func (o LookupCloudProjectDatabaseOpensearchPatternResultOutput) ClusterId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCloudProjectDatabaseOpensearchPatternResult) string { return v.ClusterId }).(pulumi.StringOutput)
}

func (o LookupCloudProjectDatabaseOpensearchPatternResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCloudProjectDatabaseOpensearchPatternResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupCloudProjectDatabaseOpensearchPatternResultOutput) MaxIndexCount() pulumi.Float64Output {
	return o.ApplyT(func(v LookupCloudProjectDatabaseOpensearchPatternResult) float64 { return v.MaxIndexCount }).(pulumi.Float64Output)
}

func (o LookupCloudProjectDatabaseOpensearchPatternResultOutput) Pattern() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCloudProjectDatabaseOpensearchPatternResult) string { return v.Pattern }).(pulumi.StringOutput)
}

func (o LookupCloudProjectDatabaseOpensearchPatternResultOutput) ServiceName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupCloudProjectDatabaseOpensearchPatternResult) *string { return v.ServiceName }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupCloudProjectDatabaseOpensearchPatternResultOutput{})
}
