// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package ovh

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/ovh/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupCloudProjectFailoverIpAttach(ctx *pulumi.Context, args *LookupCloudProjectFailoverIpAttachArgs, opts ...pulumi.InvokeOption) (*LookupCloudProjectFailoverIpAttachResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv LookupCloudProjectFailoverIpAttachResult
	err = ctx.InvokePackage("ovh:index/getCloudProjectFailoverIpAttach:getCloudProjectFailoverIpAttach", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getCloudProjectFailoverIpAttach.
type LookupCloudProjectFailoverIpAttachArgs struct {
	Block         *string `pulumi:"block"`
	ContinentCode *string `pulumi:"continentCode"`
	GeoLoc        *string `pulumi:"geoLoc"`
	Ip            *string `pulumi:"ip"`
	RoutedTo      *string `pulumi:"routedTo"`
	ServiceName   string  `pulumi:"serviceName"`
}

// A collection of values returned by getCloudProjectFailoverIpAttach.
type LookupCloudProjectFailoverIpAttachResult struct {
	Block         string  `pulumi:"block"`
	ContinentCode string  `pulumi:"continentCode"`
	GeoLoc        string  `pulumi:"geoLoc"`
	Id            string  `pulumi:"id"`
	Ip            string  `pulumi:"ip"`
	Progress      float64 `pulumi:"progress"`
	RoutedTo      string  `pulumi:"routedTo"`
	ServiceName   string  `pulumi:"serviceName"`
	Status        string  `pulumi:"status"`
	SubType       string  `pulumi:"subType"`
}

func LookupCloudProjectFailoverIpAttachOutput(ctx *pulumi.Context, args LookupCloudProjectFailoverIpAttachOutputArgs, opts ...pulumi.InvokeOption) LookupCloudProjectFailoverIpAttachResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupCloudProjectFailoverIpAttachResult, error) {
			args := v.(LookupCloudProjectFailoverIpAttachArgs)
			r, err := LookupCloudProjectFailoverIpAttach(ctx, &args, opts...)
			var s LookupCloudProjectFailoverIpAttachResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupCloudProjectFailoverIpAttachResultOutput)
}

// A collection of arguments for invoking getCloudProjectFailoverIpAttach.
type LookupCloudProjectFailoverIpAttachOutputArgs struct {
	Block         pulumi.StringPtrInput `pulumi:"block"`
	ContinentCode pulumi.StringPtrInput `pulumi:"continentCode"`
	GeoLoc        pulumi.StringPtrInput `pulumi:"geoLoc"`
	Ip            pulumi.StringPtrInput `pulumi:"ip"`
	RoutedTo      pulumi.StringPtrInput `pulumi:"routedTo"`
	ServiceName   pulumi.StringInput    `pulumi:"serviceName"`
}

func (LookupCloudProjectFailoverIpAttachOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupCloudProjectFailoverIpAttachArgs)(nil)).Elem()
}

// A collection of values returned by getCloudProjectFailoverIpAttach.
type LookupCloudProjectFailoverIpAttachResultOutput struct{ *pulumi.OutputState }

func (LookupCloudProjectFailoverIpAttachResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupCloudProjectFailoverIpAttachResult)(nil)).Elem()
}

func (o LookupCloudProjectFailoverIpAttachResultOutput) ToLookupCloudProjectFailoverIpAttachResultOutput() LookupCloudProjectFailoverIpAttachResultOutput {
	return o
}

func (o LookupCloudProjectFailoverIpAttachResultOutput) ToLookupCloudProjectFailoverIpAttachResultOutputWithContext(ctx context.Context) LookupCloudProjectFailoverIpAttachResultOutput {
	return o
}

func (o LookupCloudProjectFailoverIpAttachResultOutput) Block() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCloudProjectFailoverIpAttachResult) string { return v.Block }).(pulumi.StringOutput)
}

func (o LookupCloudProjectFailoverIpAttachResultOutput) ContinentCode() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCloudProjectFailoverIpAttachResult) string { return v.ContinentCode }).(pulumi.StringOutput)
}

func (o LookupCloudProjectFailoverIpAttachResultOutput) GeoLoc() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCloudProjectFailoverIpAttachResult) string { return v.GeoLoc }).(pulumi.StringOutput)
}

func (o LookupCloudProjectFailoverIpAttachResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCloudProjectFailoverIpAttachResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupCloudProjectFailoverIpAttachResultOutput) Ip() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCloudProjectFailoverIpAttachResult) string { return v.Ip }).(pulumi.StringOutput)
}

func (o LookupCloudProjectFailoverIpAttachResultOutput) Progress() pulumi.Float64Output {
	return o.ApplyT(func(v LookupCloudProjectFailoverIpAttachResult) float64 { return v.Progress }).(pulumi.Float64Output)
}

func (o LookupCloudProjectFailoverIpAttachResultOutput) RoutedTo() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCloudProjectFailoverIpAttachResult) string { return v.RoutedTo }).(pulumi.StringOutput)
}

func (o LookupCloudProjectFailoverIpAttachResultOutput) ServiceName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCloudProjectFailoverIpAttachResult) string { return v.ServiceName }).(pulumi.StringOutput)
}

func (o LookupCloudProjectFailoverIpAttachResultOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCloudProjectFailoverIpAttachResult) string { return v.Status }).(pulumi.StringOutput)
}

func (o LookupCloudProjectFailoverIpAttachResultOutput) SubType() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCloudProjectFailoverIpAttachResult) string { return v.SubType }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupCloudProjectFailoverIpAttachResultOutput{})
}
