// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package ovh

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/ovh/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetDbaasLogsInputEngine(ctx *pulumi.Context, args *GetDbaasLogsInputEngineArgs, opts ...pulumi.InvokeOption) (*GetDbaasLogsInputEngineResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv GetDbaasLogsInputEngineResult
	err = ctx.InvokePackage("ovh:index/getDbaasLogsInputEngine:getDbaasLogsInputEngine", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getDbaasLogsInputEngine.
type GetDbaasLogsInputEngineArgs struct {
	Id           *string `pulumi:"id"`
	IsDeprecated *bool   `pulumi:"isDeprecated"`
	Name         *string `pulumi:"name"`
	ServiceName  string  `pulumi:"serviceName"`
	Version      *string `pulumi:"version"`
}

// A collection of values returned by getDbaasLogsInputEngine.
type GetDbaasLogsInputEngineResult struct {
	Id           string `pulumi:"id"`
	IsDeprecated bool   `pulumi:"isDeprecated"`
	Name         string `pulumi:"name"`
	ServiceName  string `pulumi:"serviceName"`
	Version      string `pulumi:"version"`
}

func GetDbaasLogsInputEngineOutput(ctx *pulumi.Context, args GetDbaasLogsInputEngineOutputArgs, opts ...pulumi.InvokeOption) GetDbaasLogsInputEngineResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetDbaasLogsInputEngineResult, error) {
			args := v.(GetDbaasLogsInputEngineArgs)
			r, err := GetDbaasLogsInputEngine(ctx, &args, opts...)
			var s GetDbaasLogsInputEngineResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetDbaasLogsInputEngineResultOutput)
}

// A collection of arguments for invoking getDbaasLogsInputEngine.
type GetDbaasLogsInputEngineOutputArgs struct {
	Id           pulumi.StringPtrInput `pulumi:"id"`
	IsDeprecated pulumi.BoolPtrInput   `pulumi:"isDeprecated"`
	Name         pulumi.StringPtrInput `pulumi:"name"`
	ServiceName  pulumi.StringInput    `pulumi:"serviceName"`
	Version      pulumi.StringPtrInput `pulumi:"version"`
}

func (GetDbaasLogsInputEngineOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDbaasLogsInputEngineArgs)(nil)).Elem()
}

// A collection of values returned by getDbaasLogsInputEngine.
type GetDbaasLogsInputEngineResultOutput struct{ *pulumi.OutputState }

func (GetDbaasLogsInputEngineResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDbaasLogsInputEngineResult)(nil)).Elem()
}

func (o GetDbaasLogsInputEngineResultOutput) ToGetDbaasLogsInputEngineResultOutput() GetDbaasLogsInputEngineResultOutput {
	return o
}

func (o GetDbaasLogsInputEngineResultOutput) ToGetDbaasLogsInputEngineResultOutputWithContext(ctx context.Context) GetDbaasLogsInputEngineResultOutput {
	return o
}

func (o GetDbaasLogsInputEngineResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetDbaasLogsInputEngineResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetDbaasLogsInputEngineResultOutput) IsDeprecated() pulumi.BoolOutput {
	return o.ApplyT(func(v GetDbaasLogsInputEngineResult) bool { return v.IsDeprecated }).(pulumi.BoolOutput)
}

func (o GetDbaasLogsInputEngineResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetDbaasLogsInputEngineResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o GetDbaasLogsInputEngineResultOutput) ServiceName() pulumi.StringOutput {
	return o.ApplyT(func(v GetDbaasLogsInputEngineResult) string { return v.ServiceName }).(pulumi.StringOutput)
}

func (o GetDbaasLogsInputEngineResultOutput) Version() pulumi.StringOutput {
	return o.ApplyT(func(v GetDbaasLogsInputEngineResult) string { return v.Version }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetDbaasLogsInputEngineResultOutput{})
}
