// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package ovh

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/ovh/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupHostingPrivatedatabaseDatabase(ctx *pulumi.Context, args *LookupHostingPrivatedatabaseDatabaseArgs, opts ...pulumi.InvokeOption) (*LookupHostingPrivatedatabaseDatabaseResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv LookupHostingPrivatedatabaseDatabaseResult
	err = ctx.InvokePackage("ovh:index/getHostingPrivatedatabaseDatabase:getHostingPrivatedatabaseDatabase", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getHostingPrivatedatabaseDatabase.
type LookupHostingPrivatedatabaseDatabaseArgs struct {
	DatabaseName string  `pulumi:"databaseName"`
	Id           *string `pulumi:"id"`
	ServiceName  string  `pulumi:"serviceName"`
}

// A collection of values returned by getHostingPrivatedatabaseDatabase.
type LookupHostingPrivatedatabaseDatabaseResult struct {
	BackupTime   string                                  `pulumi:"backupTime"`
	CreationDate string                                  `pulumi:"creationDate"`
	DatabaseName string                                  `pulumi:"databaseName"`
	Id           string                                  `pulumi:"id"`
	QuotaUsed    float64                                 `pulumi:"quotaUsed"`
	ServiceName  string                                  `pulumi:"serviceName"`
	Users        []GetHostingPrivatedatabaseDatabaseUser `pulumi:"users"`
}

func LookupHostingPrivatedatabaseDatabaseOutput(ctx *pulumi.Context, args LookupHostingPrivatedatabaseDatabaseOutputArgs, opts ...pulumi.InvokeOption) LookupHostingPrivatedatabaseDatabaseResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupHostingPrivatedatabaseDatabaseResult, error) {
			args := v.(LookupHostingPrivatedatabaseDatabaseArgs)
			r, err := LookupHostingPrivatedatabaseDatabase(ctx, &args, opts...)
			var s LookupHostingPrivatedatabaseDatabaseResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupHostingPrivatedatabaseDatabaseResultOutput)
}

// A collection of arguments for invoking getHostingPrivatedatabaseDatabase.
type LookupHostingPrivatedatabaseDatabaseOutputArgs struct {
	DatabaseName pulumi.StringInput    `pulumi:"databaseName"`
	Id           pulumi.StringPtrInput `pulumi:"id"`
	ServiceName  pulumi.StringInput    `pulumi:"serviceName"`
}

func (LookupHostingPrivatedatabaseDatabaseOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupHostingPrivatedatabaseDatabaseArgs)(nil)).Elem()
}

// A collection of values returned by getHostingPrivatedatabaseDatabase.
type LookupHostingPrivatedatabaseDatabaseResultOutput struct{ *pulumi.OutputState }

func (LookupHostingPrivatedatabaseDatabaseResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupHostingPrivatedatabaseDatabaseResult)(nil)).Elem()
}

func (o LookupHostingPrivatedatabaseDatabaseResultOutput) ToLookupHostingPrivatedatabaseDatabaseResultOutput() LookupHostingPrivatedatabaseDatabaseResultOutput {
	return o
}

func (o LookupHostingPrivatedatabaseDatabaseResultOutput) ToLookupHostingPrivatedatabaseDatabaseResultOutputWithContext(ctx context.Context) LookupHostingPrivatedatabaseDatabaseResultOutput {
	return o
}

func (o LookupHostingPrivatedatabaseDatabaseResultOutput) BackupTime() pulumi.StringOutput {
	return o.ApplyT(func(v LookupHostingPrivatedatabaseDatabaseResult) string { return v.BackupTime }).(pulumi.StringOutput)
}

func (o LookupHostingPrivatedatabaseDatabaseResultOutput) CreationDate() pulumi.StringOutput {
	return o.ApplyT(func(v LookupHostingPrivatedatabaseDatabaseResult) string { return v.CreationDate }).(pulumi.StringOutput)
}

func (o LookupHostingPrivatedatabaseDatabaseResultOutput) DatabaseName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupHostingPrivatedatabaseDatabaseResult) string { return v.DatabaseName }).(pulumi.StringOutput)
}

func (o LookupHostingPrivatedatabaseDatabaseResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupHostingPrivatedatabaseDatabaseResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupHostingPrivatedatabaseDatabaseResultOutput) QuotaUsed() pulumi.Float64Output {
	return o.ApplyT(func(v LookupHostingPrivatedatabaseDatabaseResult) float64 { return v.QuotaUsed }).(pulumi.Float64Output)
}

func (o LookupHostingPrivatedatabaseDatabaseResultOutput) ServiceName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupHostingPrivatedatabaseDatabaseResult) string { return v.ServiceName }).(pulumi.StringOutput)
}

func (o LookupHostingPrivatedatabaseDatabaseResultOutput) Users() GetHostingPrivatedatabaseDatabaseUserArrayOutput {
	return o.ApplyT(func(v LookupHostingPrivatedatabaseDatabaseResult) []GetHostingPrivatedatabaseDatabaseUser {
		return v.Users
	}).(GetHostingPrivatedatabaseDatabaseUserArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupHostingPrivatedatabaseDatabaseResultOutput{})
}
