// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package ovh

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/ovh/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupHostingPrivatedatabaseUser(ctx *pulumi.Context, args *LookupHostingPrivatedatabaseUserArgs, opts ...pulumi.InvokeOption) (*LookupHostingPrivatedatabaseUserResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv LookupHostingPrivatedatabaseUserResult
	err = ctx.InvokePackage("ovh:index/getHostingPrivatedatabaseUser:getHostingPrivatedatabaseUser", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getHostingPrivatedatabaseUser.
type LookupHostingPrivatedatabaseUserArgs struct {
	Id          *string `pulumi:"id"`
	ServiceName string  `pulumi:"serviceName"`
	UserName    string  `pulumi:"userName"`
}

// A collection of values returned by getHostingPrivatedatabaseUser.
type LookupHostingPrivatedatabaseUserResult struct {
	CreationDate string                                  `pulumi:"creationDate"`
	Databases    []GetHostingPrivatedatabaseUserDatabase `pulumi:"databases"`
	Id           string                                  `pulumi:"id"`
	ServiceName  string                                  `pulumi:"serviceName"`
	UserName     string                                  `pulumi:"userName"`
}

func LookupHostingPrivatedatabaseUserOutput(ctx *pulumi.Context, args LookupHostingPrivatedatabaseUserOutputArgs, opts ...pulumi.InvokeOption) LookupHostingPrivatedatabaseUserResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupHostingPrivatedatabaseUserResult, error) {
			args := v.(LookupHostingPrivatedatabaseUserArgs)
			r, err := LookupHostingPrivatedatabaseUser(ctx, &args, opts...)
			var s LookupHostingPrivatedatabaseUserResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupHostingPrivatedatabaseUserResultOutput)
}

// A collection of arguments for invoking getHostingPrivatedatabaseUser.
type LookupHostingPrivatedatabaseUserOutputArgs struct {
	Id          pulumi.StringPtrInput `pulumi:"id"`
	ServiceName pulumi.StringInput    `pulumi:"serviceName"`
	UserName    pulumi.StringInput    `pulumi:"userName"`
}

func (LookupHostingPrivatedatabaseUserOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupHostingPrivatedatabaseUserArgs)(nil)).Elem()
}

// A collection of values returned by getHostingPrivatedatabaseUser.
type LookupHostingPrivatedatabaseUserResultOutput struct{ *pulumi.OutputState }

func (LookupHostingPrivatedatabaseUserResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupHostingPrivatedatabaseUserResult)(nil)).Elem()
}

func (o LookupHostingPrivatedatabaseUserResultOutput) ToLookupHostingPrivatedatabaseUserResultOutput() LookupHostingPrivatedatabaseUserResultOutput {
	return o
}

func (o LookupHostingPrivatedatabaseUserResultOutput) ToLookupHostingPrivatedatabaseUserResultOutputWithContext(ctx context.Context) LookupHostingPrivatedatabaseUserResultOutput {
	return o
}

func (o LookupHostingPrivatedatabaseUserResultOutput) CreationDate() pulumi.StringOutput {
	return o.ApplyT(func(v LookupHostingPrivatedatabaseUserResult) string { return v.CreationDate }).(pulumi.StringOutput)
}

func (o LookupHostingPrivatedatabaseUserResultOutput) Databases() GetHostingPrivatedatabaseUserDatabaseArrayOutput {
	return o.ApplyT(func(v LookupHostingPrivatedatabaseUserResult) []GetHostingPrivatedatabaseUserDatabase {
		return v.Databases
	}).(GetHostingPrivatedatabaseUserDatabaseArrayOutput)
}

func (o LookupHostingPrivatedatabaseUserResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupHostingPrivatedatabaseUserResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupHostingPrivatedatabaseUserResultOutput) ServiceName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupHostingPrivatedatabaseUserResult) string { return v.ServiceName }).(pulumi.StringOutput)
}

func (o LookupHostingPrivatedatabaseUserResultOutput) UserName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupHostingPrivatedatabaseUserResult) string { return v.UserName }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupHostingPrivatedatabaseUserResultOutput{})
}
