// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package ovh

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/ovh/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupIpMitigation(ctx *pulumi.Context, args *LookupIpMitigationArgs, opts ...pulumi.InvokeOption) (*LookupIpMitigationResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv LookupIpMitigationResult
	err = ctx.InvokePackage("ovh:index/getIpMitigation:getIpMitigation", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getIpMitigation.
type LookupIpMitigationArgs struct {
	Ip             string `pulumi:"ip"`
	IpOnMitigation string `pulumi:"ipOnMitigation"`
}

// A collection of values returned by getIpMitigation.
type LookupIpMitigationResult struct {
	Auto bool `pulumi:"auto"`
	// The provider-assigned unique ID for this managed resource.
	Id             string `pulumi:"id"`
	Ip             string `pulumi:"ip"`
	IpOnMitigation string `pulumi:"ipOnMitigation"`
	Permanent      bool   `pulumi:"permanent"`
	State          string `pulumi:"state"`
}

func LookupIpMitigationOutput(ctx *pulumi.Context, args LookupIpMitigationOutputArgs, opts ...pulumi.InvokeOption) LookupIpMitigationResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupIpMitigationResult, error) {
			args := v.(LookupIpMitigationArgs)
			r, err := LookupIpMitigation(ctx, &args, opts...)
			var s LookupIpMitigationResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupIpMitigationResultOutput)
}

// A collection of arguments for invoking getIpMitigation.
type LookupIpMitigationOutputArgs struct {
	Ip             pulumi.StringInput `pulumi:"ip"`
	IpOnMitigation pulumi.StringInput `pulumi:"ipOnMitigation"`
}

func (LookupIpMitigationOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupIpMitigationArgs)(nil)).Elem()
}

// A collection of values returned by getIpMitigation.
type LookupIpMitigationResultOutput struct{ *pulumi.OutputState }

func (LookupIpMitigationResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupIpMitigationResult)(nil)).Elem()
}

func (o LookupIpMitigationResultOutput) ToLookupIpMitigationResultOutput() LookupIpMitigationResultOutput {
	return o
}

func (o LookupIpMitigationResultOutput) ToLookupIpMitigationResultOutputWithContext(ctx context.Context) LookupIpMitigationResultOutput {
	return o
}

func (o LookupIpMitigationResultOutput) Auto() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupIpMitigationResult) bool { return v.Auto }).(pulumi.BoolOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupIpMitigationResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIpMitigationResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupIpMitigationResultOutput) Ip() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIpMitigationResult) string { return v.Ip }).(pulumi.StringOutput)
}

func (o LookupIpMitigationResultOutput) IpOnMitigation() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIpMitigationResult) string { return v.IpOnMitigation }).(pulumi.StringOutput)
}

func (o LookupIpMitigationResultOutput) Permanent() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupIpMitigationResult) bool { return v.Permanent }).(pulumi.BoolOutput)
}

func (o LookupIpMitigationResultOutput) State() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIpMitigationResult) string { return v.State }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupIpMitigationResultOutput{})
}
