// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package ovh

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/ovh/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupIpFirewall(ctx *pulumi.Context, args *LookupIpFirewallArgs, opts ...pulumi.InvokeOption) (*LookupIpFirewallResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv LookupIpFirewallResult
	err = ctx.InvokePackage("ovh:index/getIpFirewall:getIpFirewall", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getIpFirewall.
type LookupIpFirewallArgs struct {
	Ip           string `pulumi:"ip"`
	IpOnFirewall string `pulumi:"ipOnFirewall"`
}

// A collection of values returned by getIpFirewall.
type LookupIpFirewallResult struct {
	Enabled bool `pulumi:"enabled"`
	// The provider-assigned unique ID for this managed resource.
	Id           string `pulumi:"id"`
	Ip           string `pulumi:"ip"`
	IpOnFirewall string `pulumi:"ipOnFirewall"`
	State        string `pulumi:"state"`
}

func LookupIpFirewallOutput(ctx *pulumi.Context, args LookupIpFirewallOutputArgs, opts ...pulumi.InvokeOption) LookupIpFirewallResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupIpFirewallResult, error) {
			args := v.(LookupIpFirewallArgs)
			r, err := LookupIpFirewall(ctx, &args, opts...)
			var s LookupIpFirewallResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupIpFirewallResultOutput)
}

// A collection of arguments for invoking getIpFirewall.
type LookupIpFirewallOutputArgs struct {
	Ip           pulumi.StringInput `pulumi:"ip"`
	IpOnFirewall pulumi.StringInput `pulumi:"ipOnFirewall"`
}

func (LookupIpFirewallOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupIpFirewallArgs)(nil)).Elem()
}

// A collection of values returned by getIpFirewall.
type LookupIpFirewallResultOutput struct{ *pulumi.OutputState }

func (LookupIpFirewallResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupIpFirewallResult)(nil)).Elem()
}

func (o LookupIpFirewallResultOutput) ToLookupIpFirewallResultOutput() LookupIpFirewallResultOutput {
	return o
}

func (o LookupIpFirewallResultOutput) ToLookupIpFirewallResultOutputWithContext(ctx context.Context) LookupIpFirewallResultOutput {
	return o
}

func (o LookupIpFirewallResultOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupIpFirewallResult) bool { return v.Enabled }).(pulumi.BoolOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupIpFirewallResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIpFirewallResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupIpFirewallResultOutput) Ip() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIpFirewallResult) string { return v.Ip }).(pulumi.StringOutput)
}

func (o LookupIpFirewallResultOutput) IpOnFirewall() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIpFirewallResult) string { return v.IpOnFirewall }).(pulumi.StringOutput)
}

func (o LookupIpFirewallResultOutput) State() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIpFirewallResult) string { return v.State }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupIpFirewallResultOutput{})
}
