// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package ovh

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/ovh/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupIpService(ctx *pulumi.Context, args *LookupIpServiceArgs, opts ...pulumi.InvokeOption) (*LookupIpServiceResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv LookupIpServiceResult
	err = ctx.InvokePackage("ovh:index/getIpService:getIpService", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getIpService.
type LookupIpServiceArgs struct {
	Id          *string `pulumi:"id"`
	ServiceName string  `pulumi:"serviceName"`
}

// A collection of values returned by getIpService.
type LookupIpServiceResult struct {
	CanBeTerminated bool                   `pulumi:"canBeTerminated"`
	Country         string                 `pulumi:"country"`
	Description     string                 `pulumi:"description"`
	Id              string                 `pulumi:"id"`
	Ip              string                 `pulumi:"ip"`
	OrganisationId  string                 `pulumi:"organisationId"`
	RoutedTos       []GetIpServiceRoutedTo `pulumi:"routedTos"`
	ServiceName     string                 `pulumi:"serviceName"`
	Type            string                 `pulumi:"type"`
}

func LookupIpServiceOutput(ctx *pulumi.Context, args LookupIpServiceOutputArgs, opts ...pulumi.InvokeOption) LookupIpServiceResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupIpServiceResult, error) {
			args := v.(LookupIpServiceArgs)
			r, err := LookupIpService(ctx, &args, opts...)
			var s LookupIpServiceResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupIpServiceResultOutput)
}

// A collection of arguments for invoking getIpService.
type LookupIpServiceOutputArgs struct {
	Id          pulumi.StringPtrInput `pulumi:"id"`
	ServiceName pulumi.StringInput    `pulumi:"serviceName"`
}

func (LookupIpServiceOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupIpServiceArgs)(nil)).Elem()
}

// A collection of values returned by getIpService.
type LookupIpServiceResultOutput struct{ *pulumi.OutputState }

func (LookupIpServiceResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupIpServiceResult)(nil)).Elem()
}

func (o LookupIpServiceResultOutput) ToLookupIpServiceResultOutput() LookupIpServiceResultOutput {
	return o
}

func (o LookupIpServiceResultOutput) ToLookupIpServiceResultOutputWithContext(ctx context.Context) LookupIpServiceResultOutput {
	return o
}

func (o LookupIpServiceResultOutput) CanBeTerminated() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupIpServiceResult) bool { return v.CanBeTerminated }).(pulumi.BoolOutput)
}

func (o LookupIpServiceResultOutput) Country() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIpServiceResult) string { return v.Country }).(pulumi.StringOutput)
}

func (o LookupIpServiceResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIpServiceResult) string { return v.Description }).(pulumi.StringOutput)
}

func (o LookupIpServiceResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIpServiceResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupIpServiceResultOutput) Ip() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIpServiceResult) string { return v.Ip }).(pulumi.StringOutput)
}

func (o LookupIpServiceResultOutput) OrganisationId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIpServiceResult) string { return v.OrganisationId }).(pulumi.StringOutput)
}

func (o LookupIpServiceResultOutput) RoutedTos() GetIpServiceRoutedToArrayOutput {
	return o.ApplyT(func(v LookupIpServiceResult) []GetIpServiceRoutedTo { return v.RoutedTos }).(GetIpServiceRoutedToArrayOutput)
}

func (o LookupIpServiceResultOutput) ServiceName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIpServiceResult) string { return v.ServiceName }).(pulumi.StringOutput)
}

func (o LookupIpServiceResultOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIpServiceResult) string { return v.Type }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupIpServiceResultOutput{})
}
