// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package ovh

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/ovh/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetIamReferenceActions(ctx *pulumi.Context, args *GetIamReferenceActionsArgs, opts ...pulumi.InvokeOption) (*GetIamReferenceActionsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv GetIamReferenceActionsResult
	err = ctx.InvokePackage("ovh:index/getIamReferenceActions:getIamReferenceActions", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getIamReferenceActions.
type GetIamReferenceActionsArgs struct {
	Id   *string `pulumi:"id"`
	Type string  `pulumi:"type"`
}

// A collection of values returned by getIamReferenceActions.
type GetIamReferenceActionsResult struct {
	Actions []GetIamReferenceActionsAction `pulumi:"actions"`
	Id      string                         `pulumi:"id"`
	Type    string                         `pulumi:"type"`
}

func GetIamReferenceActionsOutput(ctx *pulumi.Context, args GetIamReferenceActionsOutputArgs, opts ...pulumi.InvokeOption) GetIamReferenceActionsResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetIamReferenceActionsResult, error) {
			args := v.(GetIamReferenceActionsArgs)
			r, err := GetIamReferenceActions(ctx, &args, opts...)
			var s GetIamReferenceActionsResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetIamReferenceActionsResultOutput)
}

// A collection of arguments for invoking getIamReferenceActions.
type GetIamReferenceActionsOutputArgs struct {
	Id   pulumi.StringPtrInput `pulumi:"id"`
	Type pulumi.StringInput    `pulumi:"type"`
}

func (GetIamReferenceActionsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetIamReferenceActionsArgs)(nil)).Elem()
}

// A collection of values returned by getIamReferenceActions.
type GetIamReferenceActionsResultOutput struct{ *pulumi.OutputState }

func (GetIamReferenceActionsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetIamReferenceActionsResult)(nil)).Elem()
}

func (o GetIamReferenceActionsResultOutput) ToGetIamReferenceActionsResultOutput() GetIamReferenceActionsResultOutput {
	return o
}

func (o GetIamReferenceActionsResultOutput) ToGetIamReferenceActionsResultOutputWithContext(ctx context.Context) GetIamReferenceActionsResultOutput {
	return o
}

func (o GetIamReferenceActionsResultOutput) Actions() GetIamReferenceActionsActionArrayOutput {
	return o.ApplyT(func(v GetIamReferenceActionsResult) []GetIamReferenceActionsAction { return v.Actions }).(GetIamReferenceActionsActionArrayOutput)
}

func (o GetIamReferenceActionsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetIamReferenceActionsResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetIamReferenceActionsResultOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v GetIamReferenceActionsResult) string { return v.Type }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetIamReferenceActionsResultOutput{})
}
