// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package ovh

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/ovh/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetIamReferenceResourceType(ctx *pulumi.Context, args *GetIamReferenceResourceTypeArgs, opts ...pulumi.InvokeOption) (*GetIamReferenceResourceTypeResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv GetIamReferenceResourceTypeResult
	err = ctx.InvokePackage("ovh:index/getIamReferenceResourceType:getIamReferenceResourceType", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getIamReferenceResourceType.
type GetIamReferenceResourceTypeArgs struct {
	Id *string `pulumi:"id"`
}

// A collection of values returned by getIamReferenceResourceType.
type GetIamReferenceResourceTypeResult struct {
	Id    string   `pulumi:"id"`
	Types []string `pulumi:"types"`
}

func GetIamReferenceResourceTypeOutput(ctx *pulumi.Context, args GetIamReferenceResourceTypeOutputArgs, opts ...pulumi.InvokeOption) GetIamReferenceResourceTypeResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetIamReferenceResourceTypeResult, error) {
			args := v.(GetIamReferenceResourceTypeArgs)
			r, err := GetIamReferenceResourceType(ctx, &args, opts...)
			var s GetIamReferenceResourceTypeResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetIamReferenceResourceTypeResultOutput)
}

// A collection of arguments for invoking getIamReferenceResourceType.
type GetIamReferenceResourceTypeOutputArgs struct {
	Id pulumi.StringPtrInput `pulumi:"id"`
}

func (GetIamReferenceResourceTypeOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetIamReferenceResourceTypeArgs)(nil)).Elem()
}

// A collection of values returned by getIamReferenceResourceType.
type GetIamReferenceResourceTypeResultOutput struct{ *pulumi.OutputState }

func (GetIamReferenceResourceTypeResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetIamReferenceResourceTypeResult)(nil)).Elem()
}

func (o GetIamReferenceResourceTypeResultOutput) ToGetIamReferenceResourceTypeResultOutput() GetIamReferenceResourceTypeResultOutput {
	return o
}

func (o GetIamReferenceResourceTypeResultOutput) ToGetIamReferenceResourceTypeResultOutputWithContext(ctx context.Context) GetIamReferenceResourceTypeResultOutput {
	return o
}

func (o GetIamReferenceResourceTypeResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetIamReferenceResourceTypeResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetIamReferenceResourceTypeResultOutput) Types() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetIamReferenceResourceTypeResult) []string { return v.Types }).(pulumi.StringArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetIamReferenceResourceTypeResultOutput{})
}
