// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package ovh

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/ovh/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupIamResourceGroup(ctx *pulumi.Context, args *LookupIamResourceGroupArgs, opts ...pulumi.InvokeOption) (*LookupIamResourceGroupResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv LookupIamResourceGroupResult
	err = ctx.InvokePackage("ovh:index/getIamResourceGroup:getIamResourceGroup", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getIamResourceGroup.
type LookupIamResourceGroupArgs struct {
	Id string `pulumi:"id"`
}

// A collection of values returned by getIamResourceGroup.
type LookupIamResourceGroupResult struct {
	CreatedAt string   `pulumi:"createdAt"`
	Id        string   `pulumi:"id"`
	Name      string   `pulumi:"name"`
	Owner     string   `pulumi:"owner"`
	ReadOnly  bool     `pulumi:"readOnly"`
	Resources []string `pulumi:"resources"`
	UpdatedAt string   `pulumi:"updatedAt"`
	Urn       string   `pulumi:"urn"`
}

func LookupIamResourceGroupOutput(ctx *pulumi.Context, args LookupIamResourceGroupOutputArgs, opts ...pulumi.InvokeOption) LookupIamResourceGroupResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupIamResourceGroupResult, error) {
			args := v.(LookupIamResourceGroupArgs)
			r, err := LookupIamResourceGroup(ctx, &args, opts...)
			var s LookupIamResourceGroupResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupIamResourceGroupResultOutput)
}

// A collection of arguments for invoking getIamResourceGroup.
type LookupIamResourceGroupOutputArgs struct {
	Id pulumi.StringInput `pulumi:"id"`
}

func (LookupIamResourceGroupOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupIamResourceGroupArgs)(nil)).Elem()
}

// A collection of values returned by getIamResourceGroup.
type LookupIamResourceGroupResultOutput struct{ *pulumi.OutputState }

func (LookupIamResourceGroupResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupIamResourceGroupResult)(nil)).Elem()
}

func (o LookupIamResourceGroupResultOutput) ToLookupIamResourceGroupResultOutput() LookupIamResourceGroupResultOutput {
	return o
}

func (o LookupIamResourceGroupResultOutput) ToLookupIamResourceGroupResultOutputWithContext(ctx context.Context) LookupIamResourceGroupResultOutput {
	return o
}

func (o LookupIamResourceGroupResultOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIamResourceGroupResult) string { return v.CreatedAt }).(pulumi.StringOutput)
}

func (o LookupIamResourceGroupResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIamResourceGroupResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupIamResourceGroupResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIamResourceGroupResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupIamResourceGroupResultOutput) Owner() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIamResourceGroupResult) string { return v.Owner }).(pulumi.StringOutput)
}

func (o LookupIamResourceGroupResultOutput) ReadOnly() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupIamResourceGroupResult) bool { return v.ReadOnly }).(pulumi.BoolOutput)
}

func (o LookupIamResourceGroupResultOutput) Resources() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupIamResourceGroupResult) []string { return v.Resources }).(pulumi.StringArrayOutput)
}

func (o LookupIamResourceGroupResultOutput) UpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIamResourceGroupResult) string { return v.UpdatedAt }).(pulumi.StringOutput)
}

func (o LookupIamResourceGroupResultOutput) Urn() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIamResourceGroupResult) string { return v.Urn }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupIamResourceGroupResultOutput{})
}
