// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package ovh

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/ovh/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetMeIdentityGroups(ctx *pulumi.Context, args *GetMeIdentityGroupsArgs, opts ...pulumi.InvokeOption) (*GetMeIdentityGroupsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv GetMeIdentityGroupsResult
	err = ctx.InvokePackage("ovh:index/getMeIdentityGroups:getMeIdentityGroups", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getMeIdentityGroups.
type GetMeIdentityGroupsArgs struct {
	Id *string `pulumi:"id"`
}

// A collection of values returned by getMeIdentityGroups.
type GetMeIdentityGroupsResult struct {
	Groups []string `pulumi:"groups"`
	Id     string   `pulumi:"id"`
}

func GetMeIdentityGroupsOutput(ctx *pulumi.Context, args GetMeIdentityGroupsOutputArgs, opts ...pulumi.InvokeOption) GetMeIdentityGroupsResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetMeIdentityGroupsResult, error) {
			args := v.(GetMeIdentityGroupsArgs)
			r, err := GetMeIdentityGroups(ctx, &args, opts...)
			var s GetMeIdentityGroupsResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetMeIdentityGroupsResultOutput)
}

// A collection of arguments for invoking getMeIdentityGroups.
type GetMeIdentityGroupsOutputArgs struct {
	Id pulumi.StringPtrInput `pulumi:"id"`
}

func (GetMeIdentityGroupsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetMeIdentityGroupsArgs)(nil)).Elem()
}

// A collection of values returned by getMeIdentityGroups.
type GetMeIdentityGroupsResultOutput struct{ *pulumi.OutputState }

func (GetMeIdentityGroupsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetMeIdentityGroupsResult)(nil)).Elem()
}

func (o GetMeIdentityGroupsResultOutput) ToGetMeIdentityGroupsResultOutput() GetMeIdentityGroupsResultOutput {
	return o
}

func (o GetMeIdentityGroupsResultOutput) ToGetMeIdentityGroupsResultOutputWithContext(ctx context.Context) GetMeIdentityGroupsResultOutput {
	return o
}

func (o GetMeIdentityGroupsResultOutput) Groups() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetMeIdentityGroupsResult) []string { return v.Groups }).(pulumi.StringArrayOutput)
}

func (o GetMeIdentityGroupsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetMeIdentityGroupsResult) string { return v.Id }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetMeIdentityGroupsResultOutput{})
}
