// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package ovh

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/ovh/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupMeIdentityUser(ctx *pulumi.Context, args *LookupMeIdentityUserArgs, opts ...pulumi.InvokeOption) (*LookupMeIdentityUserResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv LookupMeIdentityUserResult
	err = ctx.InvokePackage("ovh:index/getMeIdentityUser:getMeIdentityUser", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getMeIdentityUser.
type LookupMeIdentityUserArgs struct {
	Id   *string `pulumi:"id"`
	User string  `pulumi:"user"`
}

// A collection of values returned by getMeIdentityUser.
type LookupMeIdentityUserResult struct {
	Creation           string `pulumi:"creation"`
	Description        string `pulumi:"description"`
	Email              string `pulumi:"email"`
	Group              string `pulumi:"group"`
	Id                 string `pulumi:"id"`
	LastUpdate         string `pulumi:"lastUpdate"`
	Login              string `pulumi:"login"`
	PasswordLastUpdate string `pulumi:"passwordLastUpdate"`
	Status             string `pulumi:"status"`
	Urn                string `pulumi:"urn"`
	User               string `pulumi:"user"`
}

func LookupMeIdentityUserOutput(ctx *pulumi.Context, args LookupMeIdentityUserOutputArgs, opts ...pulumi.InvokeOption) LookupMeIdentityUserResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupMeIdentityUserResult, error) {
			args := v.(LookupMeIdentityUserArgs)
			r, err := LookupMeIdentityUser(ctx, &args, opts...)
			var s LookupMeIdentityUserResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupMeIdentityUserResultOutput)
}

// A collection of arguments for invoking getMeIdentityUser.
type LookupMeIdentityUserOutputArgs struct {
	Id   pulumi.StringPtrInput `pulumi:"id"`
	User pulumi.StringInput    `pulumi:"user"`
}

func (LookupMeIdentityUserOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupMeIdentityUserArgs)(nil)).Elem()
}

// A collection of values returned by getMeIdentityUser.
type LookupMeIdentityUserResultOutput struct{ *pulumi.OutputState }

func (LookupMeIdentityUserResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupMeIdentityUserResult)(nil)).Elem()
}

func (o LookupMeIdentityUserResultOutput) ToLookupMeIdentityUserResultOutput() LookupMeIdentityUserResultOutput {
	return o
}

func (o LookupMeIdentityUserResultOutput) ToLookupMeIdentityUserResultOutputWithContext(ctx context.Context) LookupMeIdentityUserResultOutput {
	return o
}

func (o LookupMeIdentityUserResultOutput) Creation() pulumi.StringOutput {
	return o.ApplyT(func(v LookupMeIdentityUserResult) string { return v.Creation }).(pulumi.StringOutput)
}

func (o LookupMeIdentityUserResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupMeIdentityUserResult) string { return v.Description }).(pulumi.StringOutput)
}

func (o LookupMeIdentityUserResultOutput) Email() pulumi.StringOutput {
	return o.ApplyT(func(v LookupMeIdentityUserResult) string { return v.Email }).(pulumi.StringOutput)
}

func (o LookupMeIdentityUserResultOutput) Group() pulumi.StringOutput {
	return o.ApplyT(func(v LookupMeIdentityUserResult) string { return v.Group }).(pulumi.StringOutput)
}

func (o LookupMeIdentityUserResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupMeIdentityUserResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupMeIdentityUserResultOutput) LastUpdate() pulumi.StringOutput {
	return o.ApplyT(func(v LookupMeIdentityUserResult) string { return v.LastUpdate }).(pulumi.StringOutput)
}

func (o LookupMeIdentityUserResultOutput) Login() pulumi.StringOutput {
	return o.ApplyT(func(v LookupMeIdentityUserResult) string { return v.Login }).(pulumi.StringOutput)
}

func (o LookupMeIdentityUserResultOutput) PasswordLastUpdate() pulumi.StringOutput {
	return o.ApplyT(func(v LookupMeIdentityUserResult) string { return v.PasswordLastUpdate }).(pulumi.StringOutput)
}

func (o LookupMeIdentityUserResultOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v LookupMeIdentityUserResult) string { return v.Status }).(pulumi.StringOutput)
}

func (o LookupMeIdentityUserResultOutput) Urn() pulumi.StringOutput {
	return o.ApplyT(func(v LookupMeIdentityUserResult) string { return v.Urn }).(pulumi.StringOutput)
}

func (o LookupMeIdentityUserResultOutput) User() pulumi.StringOutput {
	return o.ApplyT(func(v LookupMeIdentityUserResult) string { return v.User }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupMeIdentityUserResultOutput{})
}
