// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package ovh

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/ovh/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetMePaymentmeanBankaccount(ctx *pulumi.Context, args *GetMePaymentmeanBankaccountArgs, opts ...pulumi.InvokeOption) (*GetMePaymentmeanBankaccountResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv GetMePaymentmeanBankaccountResult
	err = ctx.InvokePackage("ovh:index/getMePaymentmeanBankaccount:getMePaymentmeanBankaccount", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getMePaymentmeanBankaccount.
type GetMePaymentmeanBankaccountArgs struct {
	DescriptionRegexp *string `pulumi:"descriptionRegexp"`
	Id                *string `pulumi:"id"`
	State             *string `pulumi:"state"`
	UseDefault        *bool   `pulumi:"useDefault"`
	UseOldest         *bool   `pulumi:"useOldest"`
}

// A collection of values returned by getMePaymentmeanBankaccount.
type GetMePaymentmeanBankaccountResult struct {
	Default           bool    `pulumi:"default"`
	Description       string  `pulumi:"description"`
	DescriptionRegexp *string `pulumi:"descriptionRegexp"`
	Id                string  `pulumi:"id"`
	State             string  `pulumi:"state"`
	UseDefault        *bool   `pulumi:"useDefault"`
	UseOldest         *bool   `pulumi:"useOldest"`
}

func GetMePaymentmeanBankaccountOutput(ctx *pulumi.Context, args GetMePaymentmeanBankaccountOutputArgs, opts ...pulumi.InvokeOption) GetMePaymentmeanBankaccountResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetMePaymentmeanBankaccountResult, error) {
			args := v.(GetMePaymentmeanBankaccountArgs)
			r, err := GetMePaymentmeanBankaccount(ctx, &args, opts...)
			var s GetMePaymentmeanBankaccountResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetMePaymentmeanBankaccountResultOutput)
}

// A collection of arguments for invoking getMePaymentmeanBankaccount.
type GetMePaymentmeanBankaccountOutputArgs struct {
	DescriptionRegexp pulumi.StringPtrInput `pulumi:"descriptionRegexp"`
	Id                pulumi.StringPtrInput `pulumi:"id"`
	State             pulumi.StringPtrInput `pulumi:"state"`
	UseDefault        pulumi.BoolPtrInput   `pulumi:"useDefault"`
	UseOldest         pulumi.BoolPtrInput   `pulumi:"useOldest"`
}

func (GetMePaymentmeanBankaccountOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetMePaymentmeanBankaccountArgs)(nil)).Elem()
}

// A collection of values returned by getMePaymentmeanBankaccount.
type GetMePaymentmeanBankaccountResultOutput struct{ *pulumi.OutputState }

func (GetMePaymentmeanBankaccountResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetMePaymentmeanBankaccountResult)(nil)).Elem()
}

func (o GetMePaymentmeanBankaccountResultOutput) ToGetMePaymentmeanBankaccountResultOutput() GetMePaymentmeanBankaccountResultOutput {
	return o
}

func (o GetMePaymentmeanBankaccountResultOutput) ToGetMePaymentmeanBankaccountResultOutputWithContext(ctx context.Context) GetMePaymentmeanBankaccountResultOutput {
	return o
}

func (o GetMePaymentmeanBankaccountResultOutput) Default() pulumi.BoolOutput {
	return o.ApplyT(func(v GetMePaymentmeanBankaccountResult) bool { return v.Default }).(pulumi.BoolOutput)
}

func (o GetMePaymentmeanBankaccountResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v GetMePaymentmeanBankaccountResult) string { return v.Description }).(pulumi.StringOutput)
}

func (o GetMePaymentmeanBankaccountResultOutput) DescriptionRegexp() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetMePaymentmeanBankaccountResult) *string { return v.DescriptionRegexp }).(pulumi.StringPtrOutput)
}

func (o GetMePaymentmeanBankaccountResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetMePaymentmeanBankaccountResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetMePaymentmeanBankaccountResultOutput) State() pulumi.StringOutput {
	return o.ApplyT(func(v GetMePaymentmeanBankaccountResult) string { return v.State }).(pulumi.StringOutput)
}

func (o GetMePaymentmeanBankaccountResultOutput) UseDefault() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v GetMePaymentmeanBankaccountResult) *bool { return v.UseDefault }).(pulumi.BoolPtrOutput)
}

func (o GetMePaymentmeanBankaccountResultOutput) UseOldest() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v GetMePaymentmeanBankaccountResult) *bool { return v.UseOldest }).(pulumi.BoolPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(GetMePaymentmeanBankaccountResultOutput{})
}
