// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package ovh

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/ovh/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type MeIdentityGroup struct {
	pulumi.CustomResourceState

	Creation     pulumi.StringOutput    `pulumi:"creation"`
	DefaultGroup pulumi.BoolOutput      `pulumi:"defaultGroup"`
	Description  pulumi.StringPtrOutput `pulumi:"description"`
	LastUpdate   pulumi.StringOutput    `pulumi:"lastUpdate"`
	Name         pulumi.StringOutput    `pulumi:"name"`
	OvhUrn       pulumi.StringOutput    `pulumi:"ovhUrn"`
	Role         pulumi.StringPtrOutput `pulumi:"role"`
}

// NewMeIdentityGroup registers a new resource with the given unique name, arguments, and options.
func NewMeIdentityGroup(ctx *pulumi.Context,
	name string, args *MeIdentityGroupArgs, opts ...pulumi.ResourceOption) (*MeIdentityGroup, error) {
	if args == nil {
		args = &MeIdentityGroupArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource MeIdentityGroup
	err = ctx.RegisterPackageResource("ovh:index/meIdentityGroup:MeIdentityGroup", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetMeIdentityGroup gets an existing MeIdentityGroup resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetMeIdentityGroup(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *MeIdentityGroupState, opts ...pulumi.ResourceOption) (*MeIdentityGroup, error) {
	var resource MeIdentityGroup
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("ovh:index/meIdentityGroup:MeIdentityGroup", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering MeIdentityGroup resources.
type meIdentityGroupState struct {
	Creation     *string `pulumi:"creation"`
	DefaultGroup *bool   `pulumi:"defaultGroup"`
	Description  *string `pulumi:"description"`
	LastUpdate   *string `pulumi:"lastUpdate"`
	Name         *string `pulumi:"name"`
	OvhUrn       *string `pulumi:"ovhUrn"`
	Role         *string `pulumi:"role"`
}

type MeIdentityGroupState struct {
	Creation     pulumi.StringPtrInput
	DefaultGroup pulumi.BoolPtrInput
	Description  pulumi.StringPtrInput
	LastUpdate   pulumi.StringPtrInput
	Name         pulumi.StringPtrInput
	OvhUrn       pulumi.StringPtrInput
	Role         pulumi.StringPtrInput
}

func (MeIdentityGroupState) ElementType() reflect.Type {
	return reflect.TypeOf((*meIdentityGroupState)(nil)).Elem()
}

type meIdentityGroupArgs struct {
	Description *string `pulumi:"description"`
	Name        *string `pulumi:"name"`
	Role        *string `pulumi:"role"`
}

// The set of arguments for constructing a MeIdentityGroup resource.
type MeIdentityGroupArgs struct {
	Description pulumi.StringPtrInput
	Name        pulumi.StringPtrInput
	Role        pulumi.StringPtrInput
}

func (MeIdentityGroupArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*meIdentityGroupArgs)(nil)).Elem()
}

type MeIdentityGroupInput interface {
	pulumi.Input

	ToMeIdentityGroupOutput() MeIdentityGroupOutput
	ToMeIdentityGroupOutputWithContext(ctx context.Context) MeIdentityGroupOutput
}

func (*MeIdentityGroup) ElementType() reflect.Type {
	return reflect.TypeOf((**MeIdentityGroup)(nil)).Elem()
}

func (i *MeIdentityGroup) ToMeIdentityGroupOutput() MeIdentityGroupOutput {
	return i.ToMeIdentityGroupOutputWithContext(context.Background())
}

func (i *MeIdentityGroup) ToMeIdentityGroupOutputWithContext(ctx context.Context) MeIdentityGroupOutput {
	return pulumi.ToOutputWithContext(ctx, i).(MeIdentityGroupOutput)
}

type MeIdentityGroupOutput struct{ *pulumi.OutputState }

func (MeIdentityGroupOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**MeIdentityGroup)(nil)).Elem()
}

func (o MeIdentityGroupOutput) ToMeIdentityGroupOutput() MeIdentityGroupOutput {
	return o
}

func (o MeIdentityGroupOutput) ToMeIdentityGroupOutputWithContext(ctx context.Context) MeIdentityGroupOutput {
	return o
}

func (o MeIdentityGroupOutput) Creation() pulumi.StringOutput {
	return o.ApplyT(func(v *MeIdentityGroup) pulumi.StringOutput { return v.Creation }).(pulumi.StringOutput)
}

func (o MeIdentityGroupOutput) DefaultGroup() pulumi.BoolOutput {
	return o.ApplyT(func(v *MeIdentityGroup) pulumi.BoolOutput { return v.DefaultGroup }).(pulumi.BoolOutput)
}

func (o MeIdentityGroupOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *MeIdentityGroup) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

func (o MeIdentityGroupOutput) LastUpdate() pulumi.StringOutput {
	return o.ApplyT(func(v *MeIdentityGroup) pulumi.StringOutput { return v.LastUpdate }).(pulumi.StringOutput)
}

func (o MeIdentityGroupOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *MeIdentityGroup) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func (o MeIdentityGroupOutput) OvhUrn() pulumi.StringOutput {
	return o.ApplyT(func(v *MeIdentityGroup) pulumi.StringOutput { return v.OvhUrn }).(pulumi.StringOutput)
}

func (o MeIdentityGroupOutput) Role() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *MeIdentityGroup) pulumi.StringPtrOutput { return v.Role }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*MeIdentityGroupInput)(nil)).Elem(), &MeIdentityGroup{})
	pulumi.RegisterOutputType(MeIdentityGroupOutput{})
}
