Host ${bastionName}
	HostName ${bastionIP}
	User ${bastionUser}
	ForwardAgent yes
	IdentityFile ./${keypairName}_rsa
	StrictHostKeyChecking no
	UserKnownHostsFile /dev/null
	ServerAliveInterval 60
	ServerAliveCountMax 30
